// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scene.proto

package projectproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Channel struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string   `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32    `protobuf:"varint,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	IsSensor             bool     `protobuf:"varint,10,opt,name=isSensor,proto3" json:"isSensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *Channel) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Channel) GetIsSensor() bool {
	if m != nil {
		return m.IsSensor
	}
	return false
}

type Thing struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalId           string     `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []*Channel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{1}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *Thing) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Scene struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Things               []*Thing `protobuf:"bytes,5,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scene) Reset()         { *m = Scene{} }
func (m *Scene) String() string { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()    {}
func (*Scene) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{2}
}

func (m *Scene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scene.Unmarshal(m, b)
}
func (m *Scene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scene.Marshal(b, m, deterministic)
}
func (m *Scene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scene.Merge(m, src)
}
func (m *Scene) XXX_Size() int {
	return xxx_messageInfo_Scene.Size(m)
}
func (m *Scene) XXX_DiscardUnknown() {
	xxx_messageInfo_Scene.DiscardUnknown(m)
}

var xxx_messageInfo_Scene proto.InternalMessageInfo

func (m *Scene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scene) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Scene) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Scene) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Scene) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type CreateSceneRequest struct {
	Scene                *Scene   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSceneRequest) Reset()         { *m = CreateSceneRequest{} }
func (m *CreateSceneRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSceneRequest) ProtoMessage()    {}
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{3}
}

func (m *CreateSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSceneRequest.Unmarshal(m, b)
}
func (m *CreateSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSceneRequest.Marshal(b, m, deterministic)
}
func (m *CreateSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSceneRequest.Merge(m, src)
}
func (m *CreateSceneRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSceneRequest.Size(m)
}
func (m *CreateSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSceneRequest proto.InternalMessageInfo

func (m *CreateSceneRequest) GetScene() *Scene {
	if m != nil {
		return m.Scene
	}
	return nil
}

type CreateSceneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSceneResponse) Reset()         { *m = CreateSceneResponse{} }
func (m *CreateSceneResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSceneResponse) ProtoMessage()    {}
func (*CreateSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{4}
}

func (m *CreateSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSceneResponse.Unmarshal(m, b)
}
func (m *CreateSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSceneResponse.Marshal(b, m, deterministic)
}
func (m *CreateSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSceneResponse.Merge(m, src)
}
func (m *CreateSceneResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSceneResponse.Size(m)
}
func (m *CreateSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSceneResponse proto.InternalMessageInfo

func (m *CreateSceneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateSceneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateSceneResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserScenesRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserScenesRequest) Reset()         { *m = UserScenesRequest{} }
func (m *UserScenesRequest) String() string { return proto.CompactTextString(m) }
func (*UserScenesRequest) ProtoMessage()    {}
func (*UserScenesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{5}
}

func (m *UserScenesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScenesRequest.Unmarshal(m, b)
}
func (m *UserScenesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScenesRequest.Marshal(b, m, deterministic)
}
func (m *UserScenesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScenesRequest.Merge(m, src)
}
func (m *UserScenesRequest) XXX_Size() int {
	return xxx_messageInfo_UserScenesRequest.Size(m)
}
func (m *UserScenesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScenesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserScenesRequest proto.InternalMessageInfo

func (m *UserScenesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UserScenesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type UserScenesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Scenes               []*Scene `protobuf:"bytes,3,rep,name=scenes,proto3" json:"scenes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserScenesResponse) Reset()         { *m = UserScenesResponse{} }
func (m *UserScenesResponse) String() string { return proto.CompactTextString(m) }
func (*UserScenesResponse) ProtoMessage()    {}
func (*UserScenesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{6}
}

func (m *UserScenesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScenesResponse.Unmarshal(m, b)
}
func (m *UserScenesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScenesResponse.Marshal(b, m, deterministic)
}
func (m *UserScenesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScenesResponse.Merge(m, src)
}
func (m *UserScenesResponse) XXX_Size() int {
	return xxx_messageInfo_UserScenesResponse.Size(m)
}
func (m *UserScenesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScenesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserScenesResponse proto.InternalMessageInfo

func (m *UserScenesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserScenesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UserScenesResponse) GetScenes() []*Scene {
	if m != nil {
		return m.Scenes
	}
	return nil
}

type GetSceneRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSceneRequest) Reset()         { *m = GetSceneRequest{} }
func (m *GetSceneRequest) String() string { return proto.CompactTextString(m) }
func (*GetSceneRequest) ProtoMessage()    {}
func (*GetSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{7}
}

func (m *GetSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSceneRequest.Unmarshal(m, b)
}
func (m *GetSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSceneRequest.Marshal(b, m, deterministic)
}
func (m *GetSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSceneRequest.Merge(m, src)
}
func (m *GetSceneRequest) XXX_Size() int {
	return xxx_messageInfo_GetSceneRequest.Size(m)
}
func (m *GetSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSceneRequest proto.InternalMessageInfo

func (m *GetSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetSceneRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetSceneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Scene                *Scene   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSceneResponse) Reset()         { *m = GetSceneResponse{} }
func (m *GetSceneResponse) String() string { return proto.CompactTextString(m) }
func (*GetSceneResponse) ProtoMessage()    {}
func (*GetSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{8}
}

func (m *GetSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSceneResponse.Unmarshal(m, b)
}
func (m *GetSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSceneResponse.Marshal(b, m, deterministic)
}
func (m *GetSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSceneResponse.Merge(m, src)
}
func (m *GetSceneResponse) XXX_Size() int {
	return xxx_messageInfo_GetSceneResponse.Size(m)
}
func (m *GetSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSceneResponse proto.InternalMessageInfo

func (m *GetSceneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetSceneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetSceneResponse) GetScene() *Scene {
	if m != nil {
		return m.Scene
	}
	return nil
}

type DeleteSceneRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSceneRequest) Reset()         { *m = DeleteSceneRequest{} }
func (m *DeleteSceneRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSceneRequest) ProtoMessage()    {}
func (*DeleteSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{9}
}

func (m *DeleteSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSceneRequest.Unmarshal(m, b)
}
func (m *DeleteSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSceneRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSceneRequest.Merge(m, src)
}
func (m *DeleteSceneRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSceneRequest.Size(m)
}
func (m *DeleteSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSceneRequest proto.InternalMessageInfo

func (m *DeleteSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteSceneRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeleteSceneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSceneResponse) Reset()         { *m = DeleteSceneResponse{} }
func (m *DeleteSceneResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSceneResponse) ProtoMessage()    {}
func (*DeleteSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{10}
}

func (m *DeleteSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSceneResponse.Unmarshal(m, b)
}
func (m *DeleteSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSceneResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSceneResponse.Merge(m, src)
}
func (m *DeleteSceneResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSceneResponse.Size(m)
}
func (m *DeleteSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSceneResponse proto.InternalMessageInfo

func (m *DeleteSceneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteSceneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateSceneRequest struct {
	Scene                *Scene   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSceneRequest) Reset()         { *m = UpdateSceneRequest{} }
func (m *UpdateSceneRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSceneRequest) ProtoMessage()    {}
func (*UpdateSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{11}
}

func (m *UpdateSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSceneRequest.Unmarshal(m, b)
}
func (m *UpdateSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSceneRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSceneRequest.Merge(m, src)
}
func (m *UpdateSceneRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSceneRequest.Size(m)
}
func (m *UpdateSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSceneRequest proto.InternalMessageInfo

func (m *UpdateSceneRequest) GetScene() *Scene {
	if m != nil {
		return m.Scene
	}
	return nil
}

type UpdateSceneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSceneResponse) Reset()         { *m = UpdateSceneResponse{} }
func (m *UpdateSceneResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSceneResponse) ProtoMessage()    {}
func (*UpdateSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{12}
}

func (m *UpdateSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSceneResponse.Unmarshal(m, b)
}
func (m *UpdateSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSceneResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSceneResponse.Merge(m, src)
}
func (m *UpdateSceneResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSceneResponse.Size(m)
}
func (m *UpdateSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSceneResponse proto.InternalMessageInfo

func (m *UpdateSceneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateSceneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ActivateSceneRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateSceneRequest) Reset()         { *m = ActivateSceneRequest{} }
func (m *ActivateSceneRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateSceneRequest) ProtoMessage()    {}
func (*ActivateSceneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{13}
}

func (m *ActivateSceneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateSceneRequest.Unmarshal(m, b)
}
func (m *ActivateSceneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateSceneRequest.Marshal(b, m, deterministic)
}
func (m *ActivateSceneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateSceneRequest.Merge(m, src)
}
func (m *ActivateSceneRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateSceneRequest.Size(m)
}
func (m *ActivateSceneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateSceneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateSceneRequest proto.InternalMessageInfo

func (m *ActivateSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ActivateSceneRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ActivateSceneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateSceneResponse) Reset()         { *m = ActivateSceneResponse{} }
func (m *ActivateSceneResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateSceneResponse) ProtoMessage()    {}
func (*ActivateSceneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{14}
}

func (m *ActivateSceneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateSceneResponse.Unmarshal(m, b)
}
func (m *ActivateSceneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateSceneResponse.Marshal(b, m, deterministic)
}
func (m *ActivateSceneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateSceneResponse.Merge(m, src)
}
func (m *ActivateSceneResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateSceneResponse.Size(m)
}
func (m *ActivateSceneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateSceneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateSceneResponse proto.InternalMessageInfo

func (m *ActivateSceneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ActivateSceneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ActivateScenesRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateScenesRequest) Reset()         { *m = ActivateScenesRequest{} }
func (m *ActivateScenesRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateScenesRequest) ProtoMessage()    {}
func (*ActivateScenesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{15}
}

func (m *ActivateScenesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateScenesRequest.Unmarshal(m, b)
}
func (m *ActivateScenesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateScenesRequest.Marshal(b, m, deterministic)
}
func (m *ActivateScenesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateScenesRequest.Merge(m, src)
}
func (m *ActivateScenesRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateScenesRequest.Size(m)
}
func (m *ActivateScenesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateScenesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateScenesRequest proto.InternalMessageInfo

func (m *ActivateScenesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ActivateScenesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ActivateScenesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateScenesResponse) Reset()         { *m = ActivateScenesResponse{} }
func (m *ActivateScenesResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateScenesResponse) ProtoMessage()    {}
func (*ActivateScenesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{16}
}

func (m *ActivateScenesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateScenesResponse.Unmarshal(m, b)
}
func (m *ActivateScenesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateScenesResponse.Marshal(b, m, deterministic)
}
func (m *ActivateScenesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateScenesResponse.Merge(m, src)
}
func (m *ActivateScenesResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateScenesResponse.Size(m)
}
func (m *ActivateScenesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateScenesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateScenesResponse proto.InternalMessageInfo

func (m *ActivateScenesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ActivateScenesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Channel)(nil), "projectproto.Channel")
	proto.RegisterType((*Thing)(nil), "projectproto.Thing")
	proto.RegisterType((*Scene)(nil), "projectproto.Scene")
	proto.RegisterType((*CreateSceneRequest)(nil), "projectproto.CreateSceneRequest")
	proto.RegisterType((*CreateSceneResponse)(nil), "projectproto.CreateSceneResponse")
	proto.RegisterType((*UserScenesRequest)(nil), "projectproto.UserScenesRequest")
	proto.RegisterType((*UserScenesResponse)(nil), "projectproto.UserScenesResponse")
	proto.RegisterType((*GetSceneRequest)(nil), "projectproto.GetSceneRequest")
	proto.RegisterType((*GetSceneResponse)(nil), "projectproto.GetSceneResponse")
	proto.RegisterType((*DeleteSceneRequest)(nil), "projectproto.DeleteSceneRequest")
	proto.RegisterType((*DeleteSceneResponse)(nil), "projectproto.DeleteSceneResponse")
	proto.RegisterType((*UpdateSceneRequest)(nil), "projectproto.UpdateSceneRequest")
	proto.RegisterType((*UpdateSceneResponse)(nil), "projectproto.UpdateSceneResponse")
	proto.RegisterType((*ActivateSceneRequest)(nil), "projectproto.ActivateSceneRequest")
	proto.RegisterType((*ActivateSceneResponse)(nil), "projectproto.ActivateSceneResponse")
	proto.RegisterType((*ActivateScenesRequest)(nil), "projectproto.ActivateScenesRequest")
	proto.RegisterType((*ActivateScenesResponse)(nil), "projectproto.ActivateScenesResponse")
}

func init() { proto.RegisterFile("scene.proto", fileDescriptor_d5bd834e1feb3b48) }

var fileDescriptor_d5bd834e1feb3b48 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x49, 0xd2, 0xdc, 0x25, 0x73, 0xa2, 0x75, 0xaf, 0x95, 0x45, 0xa4, 0x84, 0x3c, 0x45,
	0x0a, 0x07, 0xea, 0x83, 0x20, 0x82, 0xc8, 0x59, 0xaa, 0xaf, 0x5b, 0xcf, 0xf7, 0x34, 0x19, 0x7b,
	0x29, 0xe9, 0x6e, 0x9a, 0xdd, 0x53, 0xfa, 0x07, 0x08, 0xfe, 0xd9, 0x92, 0xc9, 0x8f, 0x4b, 0xce,
	0x13, 0x4b, 0xfa, 0xb6, 0x33, 0x3b, 0xf3, 0xdd, 0xef, 0x7c, 0x66, 0x61, 0xa6, 0x13, 0x94, 0xb8,
	0x28, 0x4a, 0x65, 0x14, 0x7b, 0x54, 0x94, 0xea, 0x1a, 0x13, 0x43, 0x51, 0xf8, 0xcb, 0x86, 0xe9,
	0x72, 0x1d, 0x4b, 0x89, 0x39, 0x7b, 0x0c, 0x76, 0x96, 0x72, 0x2b, 0xb0, 0x22, 0x5f, 0xd8, 0x59,
	0xca, 0x8e, 0xc0, 0x35, 0xeb, 0x4c, 0x5e, 0x71, 0x9b, 0x52, 0x75, 0xc0, 0x18, 0x1c, 0xc8, 0xf8,
	0x06, 0xb9, 0x43, 0x49, 0x3a, 0xb3, 0x13, 0x80, 0xef, 0xb9, 0x8a, 0xcd, 0xb7, 0x38, 0xdf, 0x20,
	0x3f, 0x08, 0xac, 0xc8, 0x12, 0xbd, 0x0c, 0x0b, 0x60, 0xa6, 0x4d, 0x99, 0xc9, 0xab, 0xba, 0xc0,
	0xa5, 0xd6, 0x7e, 0x8a, 0xbd, 0x00, 0xff, 0x52, 0xa9, 0xbc, 0xbe, 0x9f, 0x04, 0x56, 0xe4, 0x89,
	0x6d, 0xa2, 0xba, 0x4d, 0x63, 0x13, 0xd7, 0xb7, 0x53, 0xea, 0xde, 0x26, 0x2a, 0x47, 0x1b, 0x99,
	0x19, 0xee, 0x05, 0x56, 0xe4, 0x0a, 0x3a, 0x57, 0x39, 0x73, 0x57, 0x20, 0xf7, 0xeb, 0x5c, 0x75,
	0x66, 0xcf, 0xc1, 0xcb, 0xf4, 0x05, 0x4a, 0xad, 0x4a, 0x0e, 0xf4, 0x44, 0x17, 0x87, 0xd7, 0xe0,
	0x7e, 0xa5, 0xf1, 0x76, 0x21, 0x9c, 0x00, 0x14, 0xeb, 0x3b, 0x9d, 0x25, 0x71, 0xfe, 0x25, 0x6d,
	0x48, 0xf4, 0x32, 0xec, 0x15, 0x78, 0x49, 0xcd, 0x4f, 0x73, 0x27, 0x70, 0xa2, 0xd9, 0xeb, 0xe3,
	0x45, 0x9f, 0xf0, 0xa2, 0xa1, 0x2b, 0xba, 0xb2, 0xf0, 0xb7, 0x05, 0xee, 0x45, 0xb5, 0x91, 0x7d,
	0xc4, 0xd5, 0x4f, 0x89, 0x65, 0x4b, 0x9c, 0x82, 0xbd, 0xc4, 0x39, 0x4c, 0x9b, 0x57, 0x08, 0xb7,
	0x2f, 0xda, 0x90, 0x9d, 0xc2, 0x84, 0x16, 0xa5, 0xb9, 0x4b, 0x76, 0xe6, 0x43, 0x3b, 0x34, 0xa5,
	0x68, 0x4a, 0xc2, 0x0f, 0xc0, 0x96, 0x25, 0xc6, 0x06, 0xc9, 0x8f, 0xc0, 0xdb, 0x0d, 0x6a, 0xc3,
	0x5e, 0x82, 0x4b, 0x3f, 0x86, 0x9c, 0xfd, 0xa5, 0x50, 0x97, 0xd6, 0x15, 0xe1, 0x0a, 0xe6, 0x03,
	0x01, 0x5d, 0x28, 0xa9, 0xc9, 0x9e, 0xde, 0x24, 0x09, 0x6a, 0x4d, 0x1a, 0x9e, 0x68, 0xc3, 0x6a,
	0x44, 0x2c, 0x4b, 0xd5, 0x8d, 0x48, 0x41, 0x03, 0xc2, 0x69, 0x41, 0x84, 0x4b, 0x78, 0xba, 0xd2,
	0x58, 0x92, 0xa8, 0x6e, 0x6d, 0x75, 0x74, 0xac, 0x3e, 0x9d, 0x1e, 0x09, 0x7b, 0x40, 0x22, 0xbc,
	0x05, 0xd6, 0x17, 0x19, 0x69, 0xed, 0x14, 0x26, 0x34, 0x6a, 0xbb, 0xde, 0xbd, 0x34, 0x9a, 0x92,
	0xf0, 0x2d, 0x3c, 0x39, 0x47, 0x33, 0x80, 0x79, 0xaf, 0x1d, 0x87, 0x37, 0x70, 0xb8, 0x6d, 0x1c,
	0xe9, 0xb4, 0x5b, 0x9b, 0xf3, 0xdf, 0xb5, 0xbd, 0x03, 0xf6, 0x09, 0x73, 0xdc, 0xd9, 0xfb, 0xfd,
	0xac, 0x9e, 0xc1, 0x7c, 0xd0, 0x3b, 0xce, 0x6d, 0xf5, 0xf5, 0x56, 0x45, 0xfa, 0x80, 0xaf, 0x77,
	0x06, 0xf3, 0x81, 0xc0, 0x48, 0x1f, 0xef, 0xe1, 0xe8, 0x63, 0x62, 0xb2, 0x1f, 0xf1, 0x28, 0x18,
	0xe7, 0x70, 0xbc, 0xd3, 0x3d, 0x1a, 0xc7, 0x50, 0xa8, 0xfb, 0xf5, 0x87, 0xe0, 0x64, 0x69, 0x25,
	0xe2, 0x44, 0xbe, 0xa8, 0x8e, 0xff, 0x70, 0xf2, 0x19, 0x9e, 0xed, 0x0a, 0x8c, 0xb3, 0x72, 0x39,
	0x21, 0xd8, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x71, 0x5b, 0x9d, 0x3b, 0x37, 0x06, 0x00,
	0x00,
}
