// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thing.proto

package thingproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit int32

const (
	Unit_BOOL   Unit = 0
	Unit_NUMBER Unit = 1
	Unit_STRING Unit = 2
	Unit_DATA   Unit = 3
)

var Unit_name = map[int32]string{
	0: "BOOL",
	1: "NUMBER",
	2: "STRING",
	3: "DATA",
}

var Unit_value = map[string]int32{
	"BOOL":   0,
	"NUMBER": 1,
	"STRING": 2,
	"DATA":   3,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

type Channel struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string   `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,8,opt,name=unit,proto3,enum=thingproto.Unit" json:"unit,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	IsSensor             bool     `protobuf:"varint,10,opt,name=isSensor,proto3" json:"isSensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ChannelFromBytes(data []byte) (*Channel, error) {
	t := &Channel{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Channel) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Channel) Reset()                   { *m = Channel{} }
func (m *Channel) String() string           { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()              {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

func (m *Channel) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Channel) GetIsSensor() bool {
	if m != nil {
		return m.IsSensor
	}
	return false
}

type Thing struct {
	// @inject_tag: bson:"_id"
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Secret               string     `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Project              string     `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Channels             []*Channel `protobuf:"bytes,5,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func ThingFromBytes(data []byte) (*Thing, error) {
	t := &Thing{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Thing) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Thing) Reset()                   { *m = Thing{} }
func (m *Thing) String() string           { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()              {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{1}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Thing) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Series struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,3,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,4,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,5,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,6,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,7,opt,name=unit,proto3,enum=thingproto.Unit" json:"unit,omitempty"`
	TimeStamp            string   `protobuf:"bytes,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func SeriesFromBytes(data []byte) (*Series, error) {
	t := &Series{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Series) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Series) Reset()                   { *m = Series{} }
func (m *Series) String() string           { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()              {}
func (*Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{2}
}

func (m *Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Series.Unmarshal(m, b)
}
func (m *Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Series.Marshal(b, m, deterministic)
}
func (m *Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Series.Merge(m, src)
}
func (m *Series) XXX_Size() int {
	return xxx_messageInfo_Series.Size(m)
}
func (m *Series) XXX_DiscardUnknown() {
	xxx_messageInfo_Series.DiscardUnknown(m)
}

var xxx_messageInfo_Series proto.InternalMessageInfo

func (m *Series) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Series) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Series) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Series) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Series) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Series) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Series) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

func (m *Series) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type CreateThingRequest struct {
	Thing                *Thing   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateThingRequestFromBytes(data []byte) (*CreateThingRequest, error) {
	t := &CreateThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateThingRequest) Reset()                   { *m = CreateThingRequest{} }
func (m *CreateThingRequest) String() string           { return proto.CompactTextString(m) }
func (*CreateThingRequest) ProtoMessage()              {}
func (*CreateThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{3}
}

func (m *CreateThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingRequest.Unmarshal(m, b)
}
func (m *CreateThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingRequest.Marshal(b, m, deterministic)
}
func (m *CreateThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingRequest.Merge(m, src)
}
func (m *CreateThingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThingRequest.Size(m)
}
func (m *CreateThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingRequest proto.InternalMessageInfo

func (m *CreateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type CreateThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateThingResponseFromBytes(data []byte) (*CreateThingResponse, error) {
	t := &CreateThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateThingResponse) Reset()                   { *m = CreateThingResponse{} }
func (m *CreateThingResponse) String() string           { return proto.CompactTextString(m) }
func (*CreateThingResponse) ProtoMessage()              {}
func (*CreateThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{4}
}

func (m *CreateThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingResponse.Unmarshal(m, b)
}
func (m *CreateThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingResponse.Marshal(b, m, deterministic)
}
func (m *CreateThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingResponse.Merge(m, src)
}
func (m *CreateThingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateThingResponse.Size(m)
}
func (m *CreateThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingResponse proto.InternalMessageInfo

func (m *CreateThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateThingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetThingRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GetThingRequestFromBytes(data []byte) (*GetThingRequest, error) {
	t := &GetThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GetThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GetThingRequest) Reset()                   { *m = GetThingRequest{} }
func (m *GetThingRequest) String() string           { return proto.CompactTextString(m) }
func (*GetThingRequest) ProtoMessage()              {}
func (*GetThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{5}
}

func (m *GetThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingRequest.Unmarshal(m, b)
}
func (m *GetThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingRequest.Marshal(b, m, deterministic)
}
func (m *GetThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingRequest.Merge(m, src)
}
func (m *GetThingRequest) XXX_Size() int {
	return xxx_messageInfo_GetThingRequest.Size(m)
}
func (m *GetThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingRequest proto.InternalMessageInfo

func (m *GetThingRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

type GetThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Thing                *Thing   `protobuf:"bytes,3,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GetThingResponseFromBytes(data []byte) (*GetThingResponse, error) {
	t := &GetThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GetThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GetThingResponse) Reset()                   { *m = GetThingResponse{} }
func (m *GetThingResponse) String() string           { return proto.CompactTextString(m) }
func (*GetThingResponse) ProtoMessage()              {}
func (*GetThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{6}
}

func (m *GetThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingResponse.Unmarshal(m, b)
}
func (m *GetThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingResponse.Marshal(b, m, deterministic)
}
func (m *GetThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingResponse.Merge(m, src)
}
func (m *GetThingResponse) XXX_Size() int {
	return xxx_messageInfo_GetThingResponse.Size(m)
}
func (m *GetThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingResponse proto.InternalMessageInfo

func (m *GetThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetThingResponse) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type ProjectThingsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectThingsRequestFromBytes(data []byte) (*ProjectThingsRequest, error) {
	t := &ProjectThingsRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectThingsRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectThingsRequest) Reset()                   { *m = ProjectThingsRequest{} }
func (m *ProjectThingsRequest) String() string           { return proto.CompactTextString(m) }
func (*ProjectThingsRequest) ProtoMessage()              {}
func (*ProjectThingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{7}
}

func (m *ProjectThingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsRequest.Unmarshal(m, b)
}
func (m *ProjectThingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsRequest.Marshal(b, m, deterministic)
}
func (m *ProjectThingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsRequest.Merge(m, src)
}
func (m *ProjectThingsRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsRequest.Size(m)
}
func (m *ProjectThingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsRequest proto.InternalMessageInfo

func (m *ProjectThingsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectThingsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*Thing `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectThingsResponseFromBytes(data []byte) (*ProjectThingsResponse, error) {
	t := &ProjectThingsResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectThingsResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectThingsResponse) Reset()                   { *m = ProjectThingsResponse{} }
func (m *ProjectThingsResponse) String() string           { return proto.CompactTextString(m) }
func (*ProjectThingsResponse) ProtoMessage()              {}
func (*ProjectThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{8}
}

func (m *ProjectThingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsResponse.Unmarshal(m, b)
}
func (m *ProjectThingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsResponse.Marshal(b, m, deterministic)
}
func (m *ProjectThingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsResponse.Merge(m, src)
}
func (m *ProjectThingsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsResponse.Size(m)
}
func (m *ProjectThingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsResponse proto.InternalMessageInfo

func (m *ProjectThingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectThingsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type ProjectDeleteRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectDeleteRequestFromBytes(data []byte) (*ProjectDeleteRequest, error) {
	t := &ProjectDeleteRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectDeleteRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectDeleteRequest) Reset()                   { *m = ProjectDeleteRequest{} }
func (m *ProjectDeleteRequest) String() string           { return proto.CompactTextString(m) }
func (*ProjectDeleteRequest) ProtoMessage()              {}
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{9}
}

func (m *ProjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteRequest.Unmarshal(m, b)
}
func (m *ProjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteRequest.Merge(m, src)
}
func (m *ProjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteRequest.Size(m)
}
func (m *ProjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteRequest proto.InternalMessageInfo

func (m *ProjectDeleteRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectDeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectDeleteResponseFromBytes(data []byte) (*ProjectDeleteResponse, error) {
	t := &ProjectDeleteResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectDeleteResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectDeleteResponse) Reset()                   { *m = ProjectDeleteResponse{} }
func (m *ProjectDeleteResponse) String() string           { return proto.CompactTextString(m) }
func (*ProjectDeleteResponse) ProtoMessage()              {}
func (*ProjectDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{10}
}

func (m *ProjectDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteResponse.Unmarshal(m, b)
}
func (m *ProjectDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteResponse.Merge(m, src)
}
func (m *ProjectDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteResponse.Size(m)
}
func (m *ProjectDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteResponse proto.InternalMessageInfo

func (m *ProjectDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteThingRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteThingRequestFromBytes(data []byte) (*DeleteThingRequest, error) {
	t := &DeleteThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteThingRequest) Reset()                   { *m = DeleteThingRequest{} }
func (m *DeleteThingRequest) String() string           { return proto.CompactTextString(m) }
func (*DeleteThingRequest) ProtoMessage()              {}
func (*DeleteThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{11}
}

func (m *DeleteThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThingRequest.Unmarshal(m, b)
}
func (m *DeleteThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThingRequest.Merge(m, src)
}
func (m *DeleteThingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteThingRequest.Size(m)
}
func (m *DeleteThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThingRequest proto.InternalMessageInfo

func (m *DeleteThingRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

type DeleteThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteThingResponseFromBytes(data []byte) (*DeleteThingResponse, error) {
	t := &DeleteThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteThingResponse) Reset()                   { *m = DeleteThingResponse{} }
func (m *DeleteThingResponse) String() string           { return proto.CompactTextString(m) }
func (*DeleteThingResponse) ProtoMessage()              {}
func (*DeleteThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{12}
}

func (m *DeleteThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThingResponse.Unmarshal(m, b)
}
func (m *DeleteThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThingResponse.Merge(m, src)
}
func (m *DeleteThingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteThingResponse.Size(m)
}
func (m *DeleteThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThingResponse proto.InternalMessageInfo

func (m *DeleteThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ThingChannels struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channels             []*Channel `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func ThingChannelsFromBytes(data []byte) (*ThingChannels, error) {
	t := &ThingChannels{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ThingChannels) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ThingChannels) Reset()                   { *m = ThingChannels{} }
func (m *ThingChannels) String() string           { return proto.CompactTextString(m) }
func (*ThingChannels) ProtoMessage()              {}
func (*ThingChannels) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{13}
}

func (m *ThingChannels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingChannels.Unmarshal(m, b)
}
func (m *ThingChannels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingChannels.Marshal(b, m, deterministic)
}
func (m *ThingChannels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingChannels.Merge(m, src)
}
func (m *ThingChannels) XXX_Size() int {
	return xxx_messageInfo_ThingChannels.Size(m)
}
func (m *ThingChannels) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingChannels.DiscardUnknown(m)
}

var xxx_messageInfo_ThingChannels proto.InternalMessageInfo

func (m *ThingChannels) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThingChannels) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type UpdateChannelsRequest struct {
	Thing                string     `protobuf:"bytes,1,opt,name=Thing,proto3" json:"Thing,omitempty"`
	Channels             []*Channel `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func UpdateChannelsRequestFromBytes(data []byte) (*UpdateChannelsRequest, error) {
	t := &UpdateChannelsRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateChannelsRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateChannelsRequest) Reset()                   { *m = UpdateChannelsRequest{} }
func (m *UpdateChannelsRequest) String() string           { return proto.CompactTextString(m) }
func (*UpdateChannelsRequest) ProtoMessage()              {}
func (*UpdateChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{14}
}

func (m *UpdateChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelsRequest.Unmarshal(m, b)
}
func (m *UpdateChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelsRequest.Merge(m, src)
}
func (m *UpdateChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelsRequest.Size(m)
}
func (m *UpdateChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelsRequest proto.InternalMessageInfo

func (m *UpdateChannelsRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *UpdateChannelsRequest) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type UpdateChannelsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func UpdateChannelsResponseFromBytes(data []byte) (*UpdateChannelsResponse, error) {
	t := &UpdateChannelsResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateChannelsResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateChannelsResponse) Reset()                   { *m = UpdateChannelsResponse{} }
func (m *UpdateChannelsResponse) String() string           { return proto.CompactTextString(m) }
func (*UpdateChannelsResponse) ProtoMessage()              {}
func (*UpdateChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{15}
}

func (m *UpdateChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelsResponse.Unmarshal(m, b)
}
func (m *UpdateChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelsResponse.Merge(m, src)
}
func (m *UpdateChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelsResponse.Size(m)
}
func (m *UpdateChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelsResponse proto.InternalMessageInfo

func (m *UpdateChannelsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateChannelsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateThingsChannelsRequest struct {
	Things               []*ThingChannels `protobuf:"bytes,1,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func UpdateThingsChannelsRequestFromBytes(data []byte) (*UpdateThingsChannelsRequest, error) {
	t := &UpdateThingsChannelsRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateThingsChannelsRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateThingsChannelsRequest) Reset()                   { *m = UpdateThingsChannelsRequest{} }
func (m *UpdateThingsChannelsRequest) String() string           { return proto.CompactTextString(m) }
func (*UpdateThingsChannelsRequest) ProtoMessage()              {}
func (*UpdateThingsChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{16}
}

func (m *UpdateThingsChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Unmarshal(m, b)
}
func (m *UpdateThingsChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateThingsChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingsChannelsRequest.Merge(m, src)
}
func (m *UpdateThingsChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Size(m)
}
func (m *UpdateThingsChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingsChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingsChannelsRequest proto.InternalMessageInfo

func (m *UpdateThingsChannelsRequest) GetThings() []*ThingChannels {
	if m != nil {
		return m.Things
	}
	return nil
}

type Result struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ResultFromBytes(data []byte) (*Result, error) {
	t := &Result{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Result) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Result) Reset()                   { *m = Result{} }
func (m *Result) String() string           { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()              {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{17}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateThingsChannelsResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Success              bool      `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func UpdateThingsChannelsResponseFromBytes(data []byte) (*UpdateThingsChannelsResponse, error) {
	t := &UpdateThingsChannelsResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateThingsChannelsResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateThingsChannelsResponse) Reset()                   { *m = UpdateThingsChannelsResponse{} }
func (m *UpdateThingsChannelsResponse) String() string           { return proto.CompactTextString(m) }
func (*UpdateThingsChannelsResponse) ProtoMessage()              {}
func (*UpdateThingsChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{18}
}

func (m *UpdateThingsChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Unmarshal(m, b)
}
func (m *UpdateThingsChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateThingsChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingsChannelsResponse.Merge(m, src)
}
func (m *UpdateThingsChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Size(m)
}
func (m *UpdateThingsChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingsChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingsChannelsResponse proto.InternalMessageInfo

func (m *UpdateThingsChannelsResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *UpdateThingsChannelsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateThingsChannelsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateAssignThingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GenerateAssignThingRequestFromBytes(data []byte) (*GenerateAssignThingRequest, error) {
	t := &GenerateAssignThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GenerateAssignThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GenerateAssignThingRequest) Reset()                   { *m = GenerateAssignThingRequest{} }
func (m *GenerateAssignThingRequest) String() string           { return proto.CompactTextString(m) }
func (*GenerateAssignThingRequest) ProtoMessage()              {}
func (*GenerateAssignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{19}
}

func (m *GenerateAssignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAssignThingRequest.Unmarshal(m, b)
}
func (m *GenerateAssignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAssignThingRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAssignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAssignThingRequest.Merge(m, src)
}
func (m *GenerateAssignThingRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAssignThingRequest.Size(m)
}
func (m *GenerateAssignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAssignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAssignThingRequest proto.InternalMessageInfo

func (m *GenerateAssignThingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenerateAssignThingRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type GenerateAssignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GenerateAssignThingResponseFromBytes(data []byte) (*GenerateAssignThingResponse, error) {
	t := &GenerateAssignThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GenerateAssignThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GenerateAssignThingResponse) Reset()                   { *m = GenerateAssignThingResponse{} }
func (m *GenerateAssignThingResponse) String() string           { return proto.CompactTextString(m) }
func (*GenerateAssignThingResponse) ProtoMessage()              {}
func (*GenerateAssignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{20}
}

func (m *GenerateAssignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAssignThingResponse.Unmarshal(m, b)
}
func (m *GenerateAssignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAssignThingResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAssignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAssignThingResponse.Merge(m, src)
}
func (m *GenerateAssignThingResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAssignThingResponse.Size(m)
}
func (m *GenerateAssignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAssignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAssignThingResponse proto.InternalMessageInfo

func (m *GenerateAssignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GenerateAssignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GenerateAssignThingResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AssignThingRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func AssignThingRequestFromBytes(data []byte) (*AssignThingRequest, error) {
	t := &AssignThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *AssignThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *AssignThingRequest) Reset()                   { *m = AssignThingRequest{} }
func (m *AssignThingRequest) String() string           { return proto.CompactTextString(m) }
func (*AssignThingRequest) ProtoMessage()              {}
func (*AssignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{21}
}

func (m *AssignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignThingRequest.Unmarshal(m, b)
}
func (m *AssignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignThingRequest.Marshal(b, m, deterministic)
}
func (m *AssignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignThingRequest.Merge(m, src)
}
func (m *AssignThingRequest) XXX_Size() int {
	return xxx_messageInfo_AssignThingRequest.Size(m)
}
func (m *AssignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignThingRequest proto.InternalMessageInfo

func (m *AssignThingRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AssignThingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AssignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func AssignThingResponseFromBytes(data []byte) (*AssignThingResponse, error) {
	t := &AssignThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *AssignThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *AssignThingResponse) Reset()                   { *m = AssignThingResponse{} }
func (m *AssignThingResponse) String() string           { return proto.CompactTextString(m) }
func (*AssignThingResponse) ProtoMessage()              {}
func (*AssignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{22}
}

func (m *AssignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignThingResponse.Unmarshal(m, b)
}
func (m *AssignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignThingResponse.Marshal(b, m, deterministic)
}
func (m *AssignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignThingResponse.Merge(m, src)
}
func (m *AssignThingResponse) XXX_Size() int {
	return xxx_messageInfo_AssignThingResponse.Size(m)
}
func (m *AssignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignThingResponse proto.InternalMessageInfo

func (m *AssignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AssignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeassignThingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeassignThingRequestFromBytes(data []byte) (*DeassignThingRequest, error) {
	t := &DeassignThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeassignThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeassignThingRequest) Reset()                   { *m = DeassignThingRequest{} }
func (m *DeassignThingRequest) String() string           { return proto.CompactTextString(m) }
func (*DeassignThingRequest) ProtoMessage()              {}
func (*DeassignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{23}
}

func (m *DeassignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeassignThingRequest.Unmarshal(m, b)
}
func (m *DeassignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeassignThingRequest.Marshal(b, m, deterministic)
}
func (m *DeassignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeassignThingRequest.Merge(m, src)
}
func (m *DeassignThingRequest) XXX_Size() int {
	return xxx_messageInfo_DeassignThingRequest.Size(m)
}
func (m *DeassignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeassignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeassignThingRequest proto.InternalMessageInfo

func (m *DeassignThingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeassignThingRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type DeassignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeassignThingResponseFromBytes(data []byte) (*DeassignThingResponse, error) {
	t := &DeassignThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeassignThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeassignThingResponse) Reset()                   { *m = DeassignThingResponse{} }
func (m *DeassignThingResponse) String() string           { return proto.CompactTextString(m) }
func (*DeassignThingResponse) ProtoMessage()              {}
func (*DeassignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{24}
}

func (m *DeassignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeassignThingResponse.Unmarshal(m, b)
}
func (m *DeassignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeassignThingResponse.Marshal(b, m, deterministic)
}
func (m *DeassignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeassignThingResponse.Merge(m, src)
}
func (m *DeassignThingResponse) XXX_Size() int {
	return xxx_messageInfo_DeassignThingResponse.Size(m)
}
func (m *DeassignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeassignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeassignThingResponse proto.InternalMessageInfo

func (m *DeassignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeassignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ThingSeriesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ThingSeriesRequestFromBytes(data []byte) (*ThingSeriesRequest, error) {
	t := &ThingSeriesRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ThingSeriesRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ThingSeriesRequest) Reset()                   { *m = ThingSeriesRequest{} }
func (m *ThingSeriesRequest) String() string           { return proto.CompactTextString(m) }
func (*ThingSeriesRequest) ProtoMessage()              {}
func (*ThingSeriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{25}
}

func (m *ThingSeriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingSeriesRequest.Unmarshal(m, b)
}
func (m *ThingSeriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingSeriesRequest.Marshal(b, m, deterministic)
}
func (m *ThingSeriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingSeriesRequest.Merge(m, src)
}
func (m *ThingSeriesRequest) XXX_Size() int {
	return xxx_messageInfo_ThingSeriesRequest.Size(m)
}
func (m *ThingSeriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingSeriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThingSeriesRequest proto.InternalMessageInfo

func (m *ThingSeriesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ThingSeriesResponse struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Values               []*Series `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func ThingSeriesResponseFromBytes(data []byte) (*ThingSeriesResponse, error) {
	t := &ThingSeriesResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ThingSeriesResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ThingSeriesResponse) Reset()                   { *m = ThingSeriesResponse{} }
func (m *ThingSeriesResponse) String() string           { return proto.CompactTextString(m) }
func (*ThingSeriesResponse) ProtoMessage()              {}
func (*ThingSeriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{26}
}

func (m *ThingSeriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingSeriesResponse.Unmarshal(m, b)
}
func (m *ThingSeriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingSeriesResponse.Marshal(b, m, deterministic)
}
func (m *ThingSeriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingSeriesResponse.Merge(m, src)
}
func (m *ThingSeriesResponse) XXX_Size() int {
	return xxx_messageInfo_ThingSeriesResponse.Size(m)
}
func (m *ThingSeriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingSeriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ThingSeriesResponse proto.InternalMessageInfo

func (m *ThingSeriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ThingSeriesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ThingSeriesResponse) GetValues() []*Series {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("thingproto.Unit", Unit_name, Unit_value)
	proto.RegisterType((*Channel)(nil), "thingproto.Channel")
	proto.RegisterType((*Thing)(nil), "thingproto.Thing")
	proto.RegisterType((*Series)(nil), "thingproto.Series")
	proto.RegisterType((*CreateThingRequest)(nil), "thingproto.CreateThingRequest")
	proto.RegisterType((*CreateThingResponse)(nil), "thingproto.CreateThingResponse")
	proto.RegisterType((*GetThingRequest)(nil), "thingproto.GetThingRequest")
	proto.RegisterType((*GetThingResponse)(nil), "thingproto.GetThingResponse")
	proto.RegisterType((*ProjectThingsRequest)(nil), "thingproto.ProjectThingsRequest")
	proto.RegisterType((*ProjectThingsResponse)(nil), "thingproto.ProjectThingsResponse")
	proto.RegisterType((*ProjectDeleteRequest)(nil), "thingproto.ProjectDeleteRequest")
	proto.RegisterType((*ProjectDeleteResponse)(nil), "thingproto.ProjectDeleteResponse")
	proto.RegisterType((*DeleteThingRequest)(nil), "thingproto.DeleteThingRequest")
	proto.RegisterType((*DeleteThingResponse)(nil), "thingproto.DeleteThingResponse")
	proto.RegisterType((*ThingChannels)(nil), "thingproto.ThingChannels")
	proto.RegisterType((*UpdateChannelsRequest)(nil), "thingproto.UpdateChannelsRequest")
	proto.RegisterType((*UpdateChannelsResponse)(nil), "thingproto.UpdateChannelsResponse")
	proto.RegisterType((*UpdateThingsChannelsRequest)(nil), "thingproto.UpdateThingsChannelsRequest")
	proto.RegisterType((*Result)(nil), "thingproto.Result")
	proto.RegisterType((*UpdateThingsChannelsResponse)(nil), "thingproto.UpdateThingsChannelsResponse")
	proto.RegisterType((*GenerateAssignThingRequest)(nil), "thingproto.GenerateAssignThingRequest")
	proto.RegisterType((*GenerateAssignThingResponse)(nil), "thingproto.GenerateAssignThingResponse")
	proto.RegisterType((*AssignThingRequest)(nil), "thingproto.AssignThingRequest")
	proto.RegisterType((*AssignThingResponse)(nil), "thingproto.AssignThingResponse")
	proto.RegisterType((*DeassignThingRequest)(nil), "thingproto.DeassignThingRequest")
	proto.RegisterType((*DeassignThingResponse)(nil), "thingproto.DeassignThingResponse")
	proto.RegisterType((*ThingSeriesRequest)(nil), "thingproto.ThingSeriesRequest")
	proto.RegisterType((*ThingSeriesResponse)(nil), "thingproto.ThingSeriesResponse")
}

func init() { proto.RegisterFile("thing.proto", fileDescriptor_65361fd47d76e14b) }

var fileDescriptor_65361fd47d76e14b = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0x9b, 0xb6, 0x57, 0x31, 0x8a, 0xbb, 0x4d, 0x61, 0x9b, 0x50, 0x15, 0x4d, 0x5a,
	0x99, 0xd0, 0x80, 0xf2, 0x0a, 0x12, 0xfb, 0x45, 0x41, 0x82, 0x6d, 0x4a, 0x5b, 0x1e, 0x91, 0xb2,
	0xf6, 0xd8, 0xc2, 0xba, 0xa4, 0x8b, 0x5d, 0xa4, 0x49, 0xfc, 0x0d, 0xbc, 0xf2, 0xbf, 0xf2, 0x84,
	0x62, 0xc7, 0xa9, 0xd3, 0xb5, 0xeb, 0x16, 0x78, 0xcb, 0x9d, 0xcf, 0x9f, 0xbf, 0xbb, 0xef, 0xb3,
	0x03, 0x55, 0x7e, 0xee, 0x07, 0x67, 0x3b, 0xa3, 0x28, 0xe4, 0x21, 0x05, 0x11, 0x88, 0x6f, 0xe7,
	0xb7, 0x01, 0xa5, 0xfd, 0x73, 0x2f, 0x08, 0x70, 0x48, 0x97, 0xc0, 0xf0, 0x07, 0x36, 0x69, 0x90,
	0x66, 0xc5, 0x35, 0xfc, 0x01, 0x5d, 0x86, 0xa2, 0xa8, 0xb4, 0x0d, 0x91, 0x92, 0x01, 0xa5, 0x50,
	0x08, 0xbc, 0x4b, 0xb4, 0x4d, 0x91, 0x14, 0xdf, 0xf4, 0x29, 0xc0, 0xb7, 0x61, 0xe8, 0xf1, 0x2f,
	0xde, 0x70, 0x8c, 0x76, 0xa1, 0x41, 0x9a, 0xc4, 0xd5, 0x32, 0xb4, 0x01, 0x55, 0xc6, 0x23, 0x3f,
	0x38, 0x93, 0x05, 0x45, 0xb1, 0x55, 0x4f, 0xd1, 0x0d, 0xa8, 0x9c, 0x86, 0xe1, 0x50, 0xae, 0x5b,
	0x0d, 0xd2, 0x2c, 0xbb, 0x93, 0x44, 0xbc, 0x3a, 0xf0, 0xb8, 0x27, 0x57, 0x4b, 0x62, 0xf7, 0x24,
	0x41, 0x37, 0xa1, 0x30, 0x0e, 0x7c, 0x6e, 0x97, 0x1b, 0xa4, 0xb9, 0xd4, 0xaa, 0xed, 0x4c, 0xda,
	0xdb, 0xe9, 0x05, 0x3e, 0x77, 0xc5, 0x6a, 0xcc, 0x9b, 0x5f, 0x8f, 0xd0, 0xae, 0x34, 0x48, 0xb3,
	0xe8, 0x8a, 0x6f, 0xba, 0x06, 0x65, 0x9f, 0x75, 0x30, 0x60, 0x61, 0x64, 0x83, 0x38, 0x34, 0x8d,
	0x9d, 0x5f, 0x04, 0x8a, 0x5d, 0xd1, 0xf1, 0xf4, 0x5c, 0x56, 0xc1, 0x62, 0xd8, 0x8f, 0x90, 0x27,
	0x83, 0x49, 0x22, 0x6a, 0x43, 0x69, 0x14, 0x85, 0xdf, 0xb1, 0xcf, 0x93, 0xe1, 0xa8, 0x30, 0x9d,
	0x59, 0x41, 0x9b, 0xd9, 0x0b, 0x28, 0xf7, 0xe5, 0xe0, 0x99, 0x5d, 0x6c, 0x98, 0xcd, 0x6a, 0xab,
	0xae, 0x33, 0x4f, 0x44, 0x71, 0xd3, 0x22, 0xe7, 0x0f, 0x01, 0xab, 0x83, 0x91, 0x8f, 0x6c, 0xa2,
	0x0c, 0xd1, 0x95, 0xb1, 0xa1, 0x94, 0x14, 0x27, 0xc4, 0x54, 0x38, 0xa5, 0x8f, 0xb9, 0x48, 0x9f,
	0xc2, 0x02, 0x7d, 0x8a, 0xb7, 0xea, 0x63, 0xcd, 0xd3, 0xa7, 0x74, 0xab, 0x3e, 0x1b, 0x50, 0xe1,
	0xfe, 0x25, 0x76, 0xb8, 0x77, 0x39, 0x12, 0x52, 0x56, 0xdc, 0x49, 0xc2, 0x79, 0x0b, 0x74, 0x3f,
	0x42, 0x8f, 0xa3, 0x90, 0xc4, 0xc5, 0xab, 0x31, 0x32, 0x4e, 0xb7, 0xf4, 0x39, 0x54, 0x5b, 0x8f,
	0x75, 0x68, 0x59, 0x28, 0xd7, 0x9d, 0x1e, 0xd4, 0x33, 0xdb, 0xd9, 0x28, 0x0c, 0x18, 0xc6, 0x13,
	0x63, 0xe3, 0x7e, 0x1f, 0x19, 0x13, 0x08, 0x65, 0x57, 0x85, 0xf1, 0x84, 0x31, 0x8a, 0xc2, 0x48,
	0x79, 0x5f, 0x04, 0x89, 0x13, 0x4c, 0xe5, 0x04, 0x67, 0x0b, 0x1e, 0xb5, 0x91, 0x67, 0x28, 0xcd,
	0x94, 0xc6, 0xb9, 0x80, 0xda, 0xa4, 0x30, 0xe7, 0xe1, 0x69, 0xb3, 0xe6, 0x82, 0x66, 0x5f, 0xc2,
	0xf2, 0x89, 0x34, 0x9e, 0x48, 0x33, 0x45, 0x4d, 0xf3, 0x27, 0xc9, 0xf8, 0xd3, 0x89, 0x60, 0x65,
	0x6a, 0x47, 0x4e, 0x8e, 0xcf, 0xc0, 0x12, 0x1c, 0x98, 0x6d, 0x0a, 0x4b, 0xcf, 0x20, 0x99, 0x14,
	0x68, 0x2c, 0x0f, 0x70, 0x88, 0x1c, 0x17, 0xb3, 0x6c, 0xa7, 0x2c, 0xd5, 0x8e, 0x7c, 0x2c, 0x9d,
	0x6d, 0xa0, 0x12, 0xe1, 0x0e, 0xca, 0x1d, 0x42, 0x3d, 0x53, 0x9b, 0xf3, 0xc8, 0x13, 0x78, 0x28,
	0x00, 0x92, 0x6b, 0xcd, 0x6e, 0x3c, 0x2a, 0xfa, 0x73, 0x60, 0xdc, 0xe5, 0x39, 0xf8, 0x0a, 0x2b,
	0xbd, 0xd1, 0xc0, 0xe3, 0xa8, 0x20, 0xb5, 0x3e, 0xba, 0x7a, 0x1f, 0xf2, 0x11, 0xbb, 0x37, 0xfe,
	0x07, 0x58, 0x9d, 0xc6, 0xcf, 0xdd, 0xfb, 0xba, 0x44, 0x92, 0xe6, 0x9a, 0xe6, 0xfb, 0x2a, 0xf5,
	0x0c, 0x11, 0xbc, 0x9e, 0xdc, 0xf0, 0x4c, 0xba, 0x43, 0x79, 0xe7, 0x08, 0x2c, 0x17, 0xd9, 0x78,
	0xc8, 0xe7, 0xbf, 0x84, 0x8a, 0xa1, 0x31, 0x87, 0xa1, 0xa9, 0x33, 0xfc, 0x09, 0x1b, 0xb3, 0x19,
	0x26, 0x1d, 0x3f, 0x87, 0x52, 0x24, 0xce, 0x53, 0x1c, 0xa9, 0xce, 0x51, 0x52, 0x71, 0x55, 0xc9,
	0xbd, 0x4f, 0x7f, 0x0f, 0x6b, 0x6d, 0x0c, 0x30, 0xf2, 0x38, 0xee, 0x32, 0xe6, 0x9f, 0x05, 0x19,
	0x5b, 0x4e, 0x1b, 0x45, 0xbb, 0x1f, 0x46, 0xf6, 0x7e, 0xf4, 0x61, 0x7d, 0x26, 0x4e, 0xce, 0xbb,
	0x1c, 0x8f, 0x36, 0xbc, 0xc0, 0x40, 0x91, 0x15, 0x81, 0xf3, 0x06, 0xe8, 0x0c, 0x92, 0x69, 0x2d,
	0xd1, 0x6a, 0x69, 0x0d, 0xcc, 0x0b, 0xbc, 0x4e, 0x50, 0xe3, 0xcf, 0xf8, 0x36, 0xfd, 0x07, 0x6a,
	0xce, 0x3b, 0x58, 0x3e, 0x40, 0xef, 0x5f, 0x66, 0xd5, 0x86, 0x95, 0x29, 0x84, 0x9c, 0x54, 0x36,
	0x81, 0x0a, 0x00, 0xf9, 0x67, 0x9e, 0x43, 0xc4, 0xb9, 0x82, 0x7a, 0xa6, 0x2a, 0xa7, 0x24, 0xdb,
	0x60, 0xfd, 0x88, 0x7f, 0xa9, 0xea, 0x79, 0xcd, 0xd8, 0x30, 0xc1, 0x4e, 0x2a, 0xb6, 0x5b, 0x50,
	0x88, 0xff, 0xae, 0xb4, 0x0c, 0x85, 0xbd, 0xe3, 0xe3, 0x4f, 0xb5, 0x07, 0x14, 0xc0, 0x3a, 0xea,
	0x7d, 0xde, 0x3b, 0x74, 0x6b, 0x24, 0xfe, 0xee, 0x74, 0xdd, 0x8f, 0x47, 0xed, 0x9a, 0x11, 0x57,
	0x1c, 0xec, 0x76, 0x77, 0x6b, 0xe6, 0xa9, 0x25, 0x90, 0x5e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x4d, 0x90, 0x91, 0xb2, 0x2f, 0x0a, 0x00, 0x00,
}
