// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thing.proto

package thingproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit int32

const (
	Unit_BOOL   Unit = 0
	Unit_NUMBER Unit = 1
	Unit_STRING Unit = 2
	Unit_DATA   Unit = 3
)

var Unit_name = map[int32]string{
	0: "BOOL",
	1: "NUMBER",
	2: "STRING",
	3: "DATA",
}

var Unit_value = map[string]int32{
	"BOOL":   0,
	"NUMBER": 1,
	"STRING": 2,
	"DATA":   3,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

type Channel struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string   `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,8,opt,name=unit,proto3,enum=thingproto.Unit" json:"unit,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	IsSensor             bool     `protobuf:"varint,10,opt,name=isSensor,proto3" json:"isSensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

func (m *Channel) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Channel) GetIsSensor() bool {
	if m != nil {
		return m.IsSensor
	}
	return false
}

type Thing struct {
	// @inject_tag: bson:"_id"
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Secret               string     `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Project              string     `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Channels             []*Channel `protobuf:"bytes,5,rep,name=channels,proto3" json:"channels,omitempty"`
	Type                 int32      `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Config               string     `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	Group                string     `protobuf:"bytes,8,opt,name=group,proto3" json:"group,omitempty"`
	PhysicalId           string     `protobuf:"bytes,9,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{1}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Thing) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *Thing) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Thing) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *Thing) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Thing) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

type Series struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,3,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,4,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,5,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,6,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,7,opt,name=unit,proto3,enum=thingproto.Unit" json:"unit,omitempty"`
	TimeStamp            string   `protobuf:"bytes,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Series) Reset()         { *m = Series{} }
func (m *Series) String() string { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()    {}
func (*Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{2}
}

func (m *Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Series.Unmarshal(m, b)
}
func (m *Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Series.Marshal(b, m, deterministic)
}
func (m *Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Series.Merge(m, src)
}
func (m *Series) XXX_Size() int {
	return xxx_messageInfo_Series.Size(m)
}
func (m *Series) XXX_DiscardUnknown() {
	xxx_messageInfo_Series.DiscardUnknown(m)
}

var xxx_messageInfo_Series proto.InternalMessageInfo

func (m *Series) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Series) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Series) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Series) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Series) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Series) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Series) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

func (m *Series) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type CreateThingRequest struct {
	Thing                *Thing   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThingRequest) Reset()         { *m = CreateThingRequest{} }
func (m *CreateThingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateThingRequest) ProtoMessage()    {}
func (*CreateThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{3}
}

func (m *CreateThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingRequest.Unmarshal(m, b)
}
func (m *CreateThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingRequest.Marshal(b, m, deterministic)
}
func (m *CreateThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingRequest.Merge(m, src)
}
func (m *CreateThingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThingRequest.Size(m)
}
func (m *CreateThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingRequest proto.InternalMessageInfo

func (m *CreateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type CreateThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Channels             []string `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThingResponse) Reset()         { *m = CreateThingResponse{} }
func (m *CreateThingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateThingResponse) ProtoMessage()    {}
func (*CreateThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{4}
}

func (m *CreateThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingResponse.Unmarshal(m, b)
}
func (m *CreateThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingResponse.Marshal(b, m, deterministic)
}
func (m *CreateThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingResponse.Merge(m, src)
}
func (m *CreateThingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateThingResponse.Size(m)
}
func (m *CreateThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingResponse proto.InternalMessageInfo

func (m *CreateThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateThingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateThingResponse) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

type ThingStrChannels struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channels             []string `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingStrChannels) Reset()         { *m = ThingStrChannels{} }
func (m *ThingStrChannels) String() string { return proto.CompactTextString(m) }
func (*ThingStrChannels) ProtoMessage()    {}
func (*ThingStrChannels) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{5}
}

func (m *ThingStrChannels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingStrChannels.Unmarshal(m, b)
}
func (m *ThingStrChannels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingStrChannels.Marshal(b, m, deterministic)
}
func (m *ThingStrChannels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingStrChannels.Merge(m, src)
}
func (m *ThingStrChannels) XXX_Size() int {
	return xxx_messageInfo_ThingStrChannels.Size(m)
}
func (m *ThingStrChannels) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingStrChannels.DiscardUnknown(m)
}

var xxx_messageInfo_ThingStrChannels proto.InternalMessageInfo

func (m *ThingStrChannels) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThingStrChannels) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

type CreateThingsRequest struct {
	Things               []*Thing `protobuf:"bytes,1,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThingsRequest) Reset()         { *m = CreateThingsRequest{} }
func (m *CreateThingsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateThingsRequest) ProtoMessage()    {}
func (*CreateThingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{6}
}

func (m *CreateThingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingsRequest.Unmarshal(m, b)
}
func (m *CreateThingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingsRequest.Marshal(b, m, deterministic)
}
func (m *CreateThingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingsRequest.Merge(m, src)
}
func (m *CreateThingsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThingsRequest.Size(m)
}
func (m *CreateThingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingsRequest proto.InternalMessageInfo

func (m *CreateThingsRequest) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type CreateThingsResponse struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*ThingStrChannels `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateThingsResponse) Reset()         { *m = CreateThingsResponse{} }
func (m *CreateThingsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateThingsResponse) ProtoMessage()    {}
func (*CreateThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{7}
}

func (m *CreateThingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingsResponse.Unmarshal(m, b)
}
func (m *CreateThingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingsResponse.Marshal(b, m, deterministic)
}
func (m *CreateThingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingsResponse.Merge(m, src)
}
func (m *CreateThingsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateThingsResponse.Size(m)
}
func (m *CreateThingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingsResponse proto.InternalMessageInfo

func (m *CreateThingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateThingsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateThingsResponse) GetThings() []*ThingStrChannels {
	if m != nil {
		return m.Things
	}
	return nil
}

type GetThingRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingRequest) Reset()         { *m = GetThingRequest{} }
func (m *GetThingRequest) String() string { return proto.CompactTextString(m) }
func (*GetThingRequest) ProtoMessage()    {}
func (*GetThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{8}
}

func (m *GetThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingRequest.Unmarshal(m, b)
}
func (m *GetThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingRequest.Marshal(b, m, deterministic)
}
func (m *GetThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingRequest.Merge(m, src)
}
func (m *GetThingRequest) XXX_Size() int {
	return xxx_messageInfo_GetThingRequest.Size(m)
}
func (m *GetThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingRequest proto.InternalMessageInfo

func (m *GetThingRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

type GetThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Thing                *Thing   `protobuf:"bytes,3,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingResponse) Reset()         { *m = GetThingResponse{} }
func (m *GetThingResponse) String() string { return proto.CompactTextString(m) }
func (*GetThingResponse) ProtoMessage()    {}
func (*GetThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{9}
}

func (m *GetThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingResponse.Unmarshal(m, b)
}
func (m *GetThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingResponse.Marshal(b, m, deterministic)
}
func (m *GetThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingResponse.Merge(m, src)
}
func (m *GetThingResponse) XXX_Size() int {
	return xxx_messageInfo_GetThingResponse.Size(m)
}
func (m *GetThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingResponse proto.InternalMessageInfo

func (m *GetThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetThingResponse) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type UpdateThingRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingRequest) Reset()         { *m = UpdateThingRequest{} }
func (m *UpdateThingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateThingRequest) ProtoMessage()    {}
func (*UpdateThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{10}
}

func (m *UpdateThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingRequest.Unmarshal(m, b)
}
func (m *UpdateThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingRequest.Merge(m, src)
}
func (m *UpdateThingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateThingRequest.Size(m)
}
func (m *UpdateThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingRequest proto.InternalMessageInfo

func (m *UpdateThingRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *UpdateThingRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UpdateThingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateThingRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type UpdateThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingResponse) Reset()         { *m = UpdateThingResponse{} }
func (m *UpdateThingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateThingResponse) ProtoMessage()    {}
func (*UpdateThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{11}
}

func (m *UpdateThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingResponse.Unmarshal(m, b)
}
func (m *UpdateThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingResponse.Merge(m, src)
}
func (m *UpdateThingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateThingResponse.Size(m)
}
func (m *UpdateThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingResponse proto.InternalMessageInfo

func (m *UpdateThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProjectThingsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectThingsRequest) Reset()         { *m = ProjectThingsRequest{} }
func (m *ProjectThingsRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectThingsRequest) ProtoMessage()    {}
func (*ProjectThingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{12}
}

func (m *ProjectThingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsRequest.Unmarshal(m, b)
}
func (m *ProjectThingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsRequest.Marshal(b, m, deterministic)
}
func (m *ProjectThingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsRequest.Merge(m, src)
}
func (m *ProjectThingsRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsRequest.Size(m)
}
func (m *ProjectThingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsRequest proto.InternalMessageInfo

func (m *ProjectThingsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectThingsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*Thing `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectThingsResponse) Reset()         { *m = ProjectThingsResponse{} }
func (m *ProjectThingsResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectThingsResponse) ProtoMessage()    {}
func (*ProjectThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{13}
}

func (m *ProjectThingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsResponse.Unmarshal(m, b)
}
func (m *ProjectThingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsResponse.Marshal(b, m, deterministic)
}
func (m *ProjectThingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsResponse.Merge(m, src)
}
func (m *ProjectThingsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsResponse.Size(m)
}
func (m *ProjectThingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsResponse proto.InternalMessageInfo

func (m *ProjectThingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectThingsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type ProjectGroupThingsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectGroupThingsRequest) Reset()         { *m = ProjectGroupThingsRequest{} }
func (m *ProjectGroupThingsRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectGroupThingsRequest) ProtoMessage()    {}
func (*ProjectGroupThingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{14}
}

func (m *ProjectGroupThingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectGroupThingsRequest.Unmarshal(m, b)
}
func (m *ProjectGroupThingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectGroupThingsRequest.Marshal(b, m, deterministic)
}
func (m *ProjectGroupThingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectGroupThingsRequest.Merge(m, src)
}
func (m *ProjectGroupThingsRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectGroupThingsRequest.Size(m)
}
func (m *ProjectGroupThingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectGroupThingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectGroupThingsRequest proto.InternalMessageInfo

func (m *ProjectGroupThingsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ProjectGroupThingsRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type ProjectGroupThingsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*Thing `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectGroupThingsResponse) Reset()         { *m = ProjectGroupThingsResponse{} }
func (m *ProjectGroupThingsResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectGroupThingsResponse) ProtoMessage()    {}
func (*ProjectGroupThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{15}
}

func (m *ProjectGroupThingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectGroupThingsResponse.Unmarshal(m, b)
}
func (m *ProjectGroupThingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectGroupThingsResponse.Marshal(b, m, deterministic)
}
func (m *ProjectGroupThingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectGroupThingsResponse.Merge(m, src)
}
func (m *ProjectGroupThingsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectGroupThingsResponse.Size(m)
}
func (m *ProjectGroupThingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectGroupThingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectGroupThingsResponse proto.InternalMessageInfo

func (m *ProjectGroupThingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectGroupThingsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectGroupThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type ProjectDeleteRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDeleteRequest) Reset()         { *m = ProjectDeleteRequest{} }
func (m *ProjectDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectDeleteRequest) ProtoMessage()    {}
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{16}
}

func (m *ProjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteRequest.Unmarshal(m, b)
}
func (m *ProjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteRequest.Merge(m, src)
}
func (m *ProjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteRequest.Size(m)
}
func (m *ProjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteRequest proto.InternalMessageInfo

func (m *ProjectDeleteRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectDeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDeleteResponse) Reset()         { *m = ProjectDeleteResponse{} }
func (m *ProjectDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectDeleteResponse) ProtoMessage()    {}
func (*ProjectDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{17}
}

func (m *ProjectDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteResponse.Unmarshal(m, b)
}
func (m *ProjectDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteResponse.Merge(m, src)
}
func (m *ProjectDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteResponse.Size(m)
}
func (m *ProjectDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteResponse proto.InternalMessageInfo

func (m *ProjectDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteThingRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteThingRequest) Reset()         { *m = DeleteThingRequest{} }
func (m *DeleteThingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteThingRequest) ProtoMessage()    {}
func (*DeleteThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{18}
}

func (m *DeleteThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThingRequest.Unmarshal(m, b)
}
func (m *DeleteThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThingRequest.Merge(m, src)
}
func (m *DeleteThingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteThingRequest.Size(m)
}
func (m *DeleteThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThingRequest proto.InternalMessageInfo

func (m *DeleteThingRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

type DeleteThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteThingResponse) Reset()         { *m = DeleteThingResponse{} }
func (m *DeleteThingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteThingResponse) ProtoMessage()    {}
func (*DeleteThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{19}
}

func (m *DeleteThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteThingResponse.Unmarshal(m, b)
}
func (m *DeleteThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteThingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteThingResponse.Merge(m, src)
}
func (m *DeleteThingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteThingResponse.Size(m)
}
func (m *DeleteThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteThingResponse proto.InternalMessageInfo

func (m *DeleteThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ThingChannels struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalId           string     `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []*Channel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ThingChannels) Reset()         { *m = ThingChannels{} }
func (m *ThingChannels) String() string { return proto.CompactTextString(m) }
func (*ThingChannels) ProtoMessage()    {}
func (*ThingChannels) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{20}
}

func (m *ThingChannels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingChannels.Unmarshal(m, b)
}
func (m *ThingChannels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingChannels.Marshal(b, m, deterministic)
}
func (m *ThingChannels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingChannels.Merge(m, src)
}
func (m *ThingChannels) XXX_Size() int {
	return xxx_messageInfo_ThingChannels.Size(m)
}
func (m *ThingChannels) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingChannels.DiscardUnknown(m)
}

var xxx_messageInfo_ThingChannels proto.InternalMessageInfo

func (m *ThingChannels) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThingChannels) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *ThingChannels) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type UpdateChannelNameRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateChannelNameRequest) Reset()         { *m = UpdateChannelNameRequest{} }
func (m *UpdateChannelNameRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelNameRequest) ProtoMessage()    {}
func (*UpdateChannelNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{21}
}

func (m *UpdateChannelNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelNameRequest.Unmarshal(m, b)
}
func (m *UpdateChannelNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelNameRequest.Marshal(b, m, deterministic)
}
func (m *UpdateChannelNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelNameRequest.Merge(m, src)
}
func (m *UpdateChannelNameRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelNameRequest.Size(m)
}
func (m *UpdateChannelNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelNameRequest proto.InternalMessageInfo

func (m *UpdateChannelNameRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *UpdateChannelNameRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *UpdateChannelNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateChannelNameRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type UpdateChannelNameResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateChannelNameResponse) Reset()         { *m = UpdateChannelNameResponse{} }
func (m *UpdateChannelNameResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelNameResponse) ProtoMessage()    {}
func (*UpdateChannelNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{22}
}

func (m *UpdateChannelNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelNameResponse.Unmarshal(m, b)
}
func (m *UpdateChannelNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelNameResponse.Marshal(b, m, deterministic)
}
func (m *UpdateChannelNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelNameResponse.Merge(m, src)
}
func (m *UpdateChannelNameResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelNameResponse.Size(m)
}
func (m *UpdateChannelNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelNameResponse proto.InternalMessageInfo

func (m *UpdateChannelNameResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateChannelNameResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateChannelsRequest struct {
	Thing                string     `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	PhysicalId           string     `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []*Channel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateChannelsRequest) Reset()         { *m = UpdateChannelsRequest{} }
func (m *UpdateChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelsRequest) ProtoMessage()    {}
func (*UpdateChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{23}
}

func (m *UpdateChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelsRequest.Unmarshal(m, b)
}
func (m *UpdateChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelsRequest.Merge(m, src)
}
func (m *UpdateChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelsRequest.Size(m)
}
func (m *UpdateChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelsRequest proto.InternalMessageInfo

func (m *UpdateChannelsRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *UpdateChannelsRequest) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *UpdateChannelsRequest) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type UpdateChannelsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateChannelsResponse) Reset()         { *m = UpdateChannelsResponse{} }
func (m *UpdateChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateChannelsResponse) ProtoMessage()    {}
func (*UpdateChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{24}
}

func (m *UpdateChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateChannelsResponse.Unmarshal(m, b)
}
func (m *UpdateChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateChannelsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateChannelsResponse.Merge(m, src)
}
func (m *UpdateChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateChannelsResponse.Size(m)
}
func (m *UpdateChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateChannelsResponse proto.InternalMessageInfo

func (m *UpdateChannelsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateChannelsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateThingsChannelsRequest struct {
	Things               []*ThingChannels `protobuf:"bytes,1,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateThingsChannelsRequest) Reset()         { *m = UpdateThingsChannelsRequest{} }
func (m *UpdateThingsChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateThingsChannelsRequest) ProtoMessage()    {}
func (*UpdateThingsChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{25}
}

func (m *UpdateThingsChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Unmarshal(m, b)
}
func (m *UpdateThingsChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateThingsChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingsChannelsRequest.Merge(m, src)
}
func (m *UpdateThingsChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateThingsChannelsRequest.Size(m)
}
func (m *UpdateThingsChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingsChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingsChannelsRequest proto.InternalMessageInfo

func (m *UpdateThingsChannelsRequest) GetThings() []*ThingChannels {
	if m != nil {
		return m.Things
	}
	return nil
}

type Result struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{26}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateThingsChannelsResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Success              bool      `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateThingsChannelsResponse) Reset()         { *m = UpdateThingsChannelsResponse{} }
func (m *UpdateThingsChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateThingsChannelsResponse) ProtoMessage()    {}
func (*UpdateThingsChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{27}
}

func (m *UpdateThingsChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Unmarshal(m, b)
}
func (m *UpdateThingsChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateThingsChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingsChannelsResponse.Merge(m, src)
}
func (m *UpdateThingsChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateThingsChannelsResponse.Size(m)
}
func (m *UpdateThingsChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingsChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingsChannelsResponse proto.InternalMessageInfo

func (m *UpdateThingsChannelsResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *UpdateThingsChannelsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateThingsChannelsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateAssignThingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAssignThingRequest) Reset()         { *m = GenerateAssignThingRequest{} }
func (m *GenerateAssignThingRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAssignThingRequest) ProtoMessage()    {}
func (*GenerateAssignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{28}
}

func (m *GenerateAssignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAssignThingRequest.Unmarshal(m, b)
}
func (m *GenerateAssignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAssignThingRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAssignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAssignThingRequest.Merge(m, src)
}
func (m *GenerateAssignThingRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAssignThingRequest.Size(m)
}
func (m *GenerateAssignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAssignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAssignThingRequest proto.InternalMessageInfo

func (m *GenerateAssignThingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenerateAssignThingRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type GenerateAssignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAssignThingResponse) Reset()         { *m = GenerateAssignThingResponse{} }
func (m *GenerateAssignThingResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAssignThingResponse) ProtoMessage()    {}
func (*GenerateAssignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{29}
}

func (m *GenerateAssignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAssignThingResponse.Unmarshal(m, b)
}
func (m *GenerateAssignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAssignThingResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAssignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAssignThingResponse.Merge(m, src)
}
func (m *GenerateAssignThingResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAssignThingResponse.Size(m)
}
func (m *GenerateAssignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAssignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAssignThingResponse proto.InternalMessageInfo

func (m *GenerateAssignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GenerateAssignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GenerateAssignThingResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AssignThingRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignThingRequest) Reset()         { *m = AssignThingRequest{} }
func (m *AssignThingRequest) String() string { return proto.CompactTextString(m) }
func (*AssignThingRequest) ProtoMessage()    {}
func (*AssignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{30}
}

func (m *AssignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignThingRequest.Unmarshal(m, b)
}
func (m *AssignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignThingRequest.Marshal(b, m, deterministic)
}
func (m *AssignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignThingRequest.Merge(m, src)
}
func (m *AssignThingRequest) XXX_Size() int {
	return xxx_messageInfo_AssignThingRequest.Size(m)
}
func (m *AssignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignThingRequest proto.InternalMessageInfo

func (m *AssignThingRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AssignThingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AssignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignThingResponse) Reset()         { *m = AssignThingResponse{} }
func (m *AssignThingResponse) String() string { return proto.CompactTextString(m) }
func (*AssignThingResponse) ProtoMessage()    {}
func (*AssignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{31}
}

func (m *AssignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignThingResponse.Unmarshal(m, b)
}
func (m *AssignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignThingResponse.Marshal(b, m, deterministic)
}
func (m *AssignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignThingResponse.Merge(m, src)
}
func (m *AssignThingResponse) XXX_Size() int {
	return xxx_messageInfo_AssignThingResponse.Size(m)
}
func (m *AssignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignThingResponse proto.InternalMessageInfo

func (m *AssignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AssignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeassignThingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeassignThingRequest) Reset()         { *m = DeassignThingRequest{} }
func (m *DeassignThingRequest) String() string { return proto.CompactTextString(m) }
func (*DeassignThingRequest) ProtoMessage()    {}
func (*DeassignThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{32}
}

func (m *DeassignThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeassignThingRequest.Unmarshal(m, b)
}
func (m *DeassignThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeassignThingRequest.Marshal(b, m, deterministic)
}
func (m *DeassignThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeassignThingRequest.Merge(m, src)
}
func (m *DeassignThingRequest) XXX_Size() int {
	return xxx_messageInfo_DeassignThingRequest.Size(m)
}
func (m *DeassignThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeassignThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeassignThingRequest proto.InternalMessageInfo

func (m *DeassignThingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeassignThingRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type DeassignThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeassignThingResponse) Reset()         { *m = DeassignThingResponse{} }
func (m *DeassignThingResponse) String() string { return proto.CompactTextString(m) }
func (*DeassignThingResponse) ProtoMessage()    {}
func (*DeassignThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{33}
}

func (m *DeassignThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeassignThingResponse.Unmarshal(m, b)
}
func (m *DeassignThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeassignThingResponse.Marshal(b, m, deterministic)
}
func (m *DeassignThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeassignThingResponse.Merge(m, src)
}
func (m *DeassignThingResponse) XXX_Size() int {
	return xxx_messageInfo_DeassignThingResponse.Size(m)
}
func (m *DeassignThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeassignThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeassignThingResponse proto.InternalMessageInfo

func (m *DeassignThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeassignThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ThingSeriesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingSeriesRequest) Reset()         { *m = ThingSeriesRequest{} }
func (m *ThingSeriesRequest) String() string { return proto.CompactTextString(m) }
func (*ThingSeriesRequest) ProtoMessage()    {}
func (*ThingSeriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{34}
}

func (m *ThingSeriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingSeriesRequest.Unmarshal(m, b)
}
func (m *ThingSeriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingSeriesRequest.Marshal(b, m, deterministic)
}
func (m *ThingSeriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingSeriesRequest.Merge(m, src)
}
func (m *ThingSeriesRequest) XXX_Size() int {
	return xxx_messageInfo_ThingSeriesRequest.Size(m)
}
func (m *ThingSeriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingSeriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThingSeriesRequest proto.InternalMessageInfo

func (m *ThingSeriesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThingSeriesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type ThingSeriesResponse struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Values               []*Series `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ThingSeriesResponse) Reset()         { *m = ThingSeriesResponse{} }
func (m *ThingSeriesResponse) String() string { return proto.CompactTextString(m) }
func (*ThingSeriesResponse) ProtoMessage()    {}
func (*ThingSeriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{35}
}

func (m *ThingSeriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingSeriesResponse.Unmarshal(m, b)
}
func (m *ThingSeriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingSeriesResponse.Marshal(b, m, deterministic)
}
func (m *ThingSeriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingSeriesResponse.Merge(m, src)
}
func (m *ThingSeriesResponse) XXX_Size() int {
	return xxx_messageInfo_ThingSeriesResponse.Size(m)
}
func (m *ThingSeriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingSeriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ThingSeriesResponse proto.InternalMessageInfo

func (m *ThingSeriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ThingSeriesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ThingSeriesResponse) GetValues() []*Series {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetThingsByIDsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingsByIDsRequest) Reset()         { *m = GetThingsByIDsRequest{} }
func (m *GetThingsByIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetThingsByIDsRequest) ProtoMessage()    {}
func (*GetThingsByIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{36}
}

func (m *GetThingsByIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingsByIDsRequest.Unmarshal(m, b)
}
func (m *GetThingsByIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingsByIDsRequest.Marshal(b, m, deterministic)
}
func (m *GetThingsByIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingsByIDsRequest.Merge(m, src)
}
func (m *GetThingsByIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetThingsByIDsRequest.Size(m)
}
func (m *GetThingsByIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingsByIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingsByIDsRequest proto.InternalMessageInfo

func (m *GetThingsByIDsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetThingsByIDsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*Thing `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingsByIDsResponse) Reset()         { *m = GetThingsByIDsResponse{} }
func (m *GetThingsByIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GetThingsByIDsResponse) ProtoMessage()    {}
func (*GetThingsByIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{37}
}

func (m *GetThingsByIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingsByIDsResponse.Unmarshal(m, b)
}
func (m *GetThingsByIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingsByIDsResponse.Marshal(b, m, deterministic)
}
func (m *GetThingsByIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingsByIDsResponse.Merge(m, src)
}
func (m *GetThingsByIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GetThingsByIDsResponse.Size(m)
}
func (m *GetThingsByIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingsByIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingsByIDsResponse proto.InternalMessageInfo

func (m *GetThingsByIDsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetThingsByIDsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetThingsByIDsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type UpdateThingConfigRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Config               string   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingConfigRequest) Reset()         { *m = UpdateThingConfigRequest{} }
func (m *UpdateThingConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateThingConfigRequest) ProtoMessage()    {}
func (*UpdateThingConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{38}
}

func (m *UpdateThingConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingConfigRequest.Unmarshal(m, b)
}
func (m *UpdateThingConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateThingConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingConfigRequest.Merge(m, src)
}
func (m *UpdateThingConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateThingConfigRequest.Size(m)
}
func (m *UpdateThingConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingConfigRequest proto.InternalMessageInfo

func (m *UpdateThingConfigRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *UpdateThingConfigRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type UpdateThingConfigResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingConfigResponse) Reset()         { *m = UpdateThingConfigResponse{} }
func (m *UpdateThingConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateThingConfigResponse) ProtoMessage()    {}
func (*UpdateThingConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{39}
}

func (m *UpdateThingConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingConfigResponse.Unmarshal(m, b)
}
func (m *UpdateThingConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateThingConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingConfigResponse.Merge(m, src)
}
func (m *UpdateThingConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateThingConfigResponse.Size(m)
}
func (m *UpdateThingConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingConfigResponse proto.InternalMessageInfo

func (m *UpdateThingConfigResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateThingConfigResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetThingTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingTypesRequest) Reset()         { *m = GetThingTypesRequest{} }
func (m *GetThingTypesRequest) String() string { return proto.CompactTextString(m) }
func (*GetThingTypesRequest) ProtoMessage()    {}
func (*GetThingTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{40}
}

func (m *GetThingTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingTypesRequest.Unmarshal(m, b)
}
func (m *GetThingTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingTypesRequest.Marshal(b, m, deterministic)
}
func (m *GetThingTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingTypesRequest.Merge(m, src)
}
func (m *GetThingTypesRequest) XXX_Size() int {
	return xxx_messageInfo_GetThingTypesRequest.Size(m)
}
func (m *GetThingTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingTypesRequest proto.InternalMessageInfo

type GetThingTypesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Types                []string `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThingTypesResponse) Reset()         { *m = GetThingTypesResponse{} }
func (m *GetThingTypesResponse) String() string { return proto.CompactTextString(m) }
func (*GetThingTypesResponse) ProtoMessage()    {}
func (*GetThingTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{41}
}

func (m *GetThingTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThingTypesResponse.Unmarshal(m, b)
}
func (m *GetThingTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThingTypesResponse.Marshal(b, m, deterministic)
}
func (m *GetThingTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThingTypesResponse.Merge(m, src)
}
func (m *GetThingTypesResponse) XXX_Size() int {
	return xxx_messageInfo_GetThingTypesResponse.Size(m)
}
func (m *GetThingTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThingTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetThingTypesResponse proto.InternalMessageInfo

func (m *GetThingTypesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetThingTypesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetThingTypesResponse) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func init() {
	proto.RegisterEnum("thingproto.Unit", Unit_name, Unit_value)
	proto.RegisterType((*Channel)(nil), "thingproto.Channel")
	proto.RegisterType((*Thing)(nil), "thingproto.Thing")
	proto.RegisterType((*Series)(nil), "thingproto.Series")
	proto.RegisterType((*CreateThingRequest)(nil), "thingproto.CreateThingRequest")
	proto.RegisterType((*CreateThingResponse)(nil), "thingproto.CreateThingResponse")
	proto.RegisterType((*ThingStrChannels)(nil), "thingproto.ThingStrChannels")
	proto.RegisterType((*CreateThingsRequest)(nil), "thingproto.CreateThingsRequest")
	proto.RegisterType((*CreateThingsResponse)(nil), "thingproto.CreateThingsResponse")
	proto.RegisterType((*GetThingRequest)(nil), "thingproto.GetThingRequest")
	proto.RegisterType((*GetThingResponse)(nil), "thingproto.GetThingResponse")
	proto.RegisterType((*UpdateThingRequest)(nil), "thingproto.UpdateThingRequest")
	proto.RegisterType((*UpdateThingResponse)(nil), "thingproto.UpdateThingResponse")
	proto.RegisterType((*ProjectThingsRequest)(nil), "thingproto.ProjectThingsRequest")
	proto.RegisterType((*ProjectThingsResponse)(nil), "thingproto.ProjectThingsResponse")
	proto.RegisterType((*ProjectGroupThingsRequest)(nil), "thingproto.ProjectGroupThingsRequest")
	proto.RegisterType((*ProjectGroupThingsResponse)(nil), "thingproto.ProjectGroupThingsResponse")
	proto.RegisterType((*ProjectDeleteRequest)(nil), "thingproto.ProjectDeleteRequest")
	proto.RegisterType((*ProjectDeleteResponse)(nil), "thingproto.ProjectDeleteResponse")
	proto.RegisterType((*DeleteThingRequest)(nil), "thingproto.DeleteThingRequest")
	proto.RegisterType((*DeleteThingResponse)(nil), "thingproto.DeleteThingResponse")
	proto.RegisterType((*ThingChannels)(nil), "thingproto.ThingChannels")
	proto.RegisterType((*UpdateChannelNameRequest)(nil), "thingproto.UpdateChannelNameRequest")
	proto.RegisterType((*UpdateChannelNameResponse)(nil), "thingproto.UpdateChannelNameResponse")
	proto.RegisterType((*UpdateChannelsRequest)(nil), "thingproto.UpdateChannelsRequest")
	proto.RegisterType((*UpdateChannelsResponse)(nil), "thingproto.UpdateChannelsResponse")
	proto.RegisterType((*UpdateThingsChannelsRequest)(nil), "thingproto.UpdateThingsChannelsRequest")
	proto.RegisterType((*Result)(nil), "thingproto.Result")
	proto.RegisterType((*UpdateThingsChannelsResponse)(nil), "thingproto.UpdateThingsChannelsResponse")
	proto.RegisterType((*GenerateAssignThingRequest)(nil), "thingproto.GenerateAssignThingRequest")
	proto.RegisterType((*GenerateAssignThingResponse)(nil), "thingproto.GenerateAssignThingResponse")
	proto.RegisterType((*AssignThingRequest)(nil), "thingproto.AssignThingRequest")
	proto.RegisterType((*AssignThingResponse)(nil), "thingproto.AssignThingResponse")
	proto.RegisterType((*DeassignThingRequest)(nil), "thingproto.DeassignThingRequest")
	proto.RegisterType((*DeassignThingResponse)(nil), "thingproto.DeassignThingResponse")
	proto.RegisterType((*ThingSeriesRequest)(nil), "thingproto.ThingSeriesRequest")
	proto.RegisterType((*ThingSeriesResponse)(nil), "thingproto.ThingSeriesResponse")
	proto.RegisterType((*GetThingsByIDsRequest)(nil), "thingproto.GetThingsByIDsRequest")
	proto.RegisterType((*GetThingsByIDsResponse)(nil), "thingproto.GetThingsByIDsResponse")
	proto.RegisterType((*UpdateThingConfigRequest)(nil), "thingproto.UpdateThingConfigRequest")
	proto.RegisterType((*UpdateThingConfigResponse)(nil), "thingproto.UpdateThingConfigResponse")
	proto.RegisterType((*GetThingTypesRequest)(nil), "thingproto.GetThingTypesRequest")
	proto.RegisterType((*GetThingTypesResponse)(nil), "thingproto.GetThingTypesResponse")
}

func init() { proto.RegisterFile("thing.proto", fileDescriptor_65361fd47d76e14b) }

var fileDescriptor_65361fd47d76e14b = []byte{
	// 1028 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6f, 0xdb, 0x36,
	0x10, 0x9f, 0x3e, 0x2c, 0xdb, 0x17, 0xac, 0xd3, 0x18, 0xc7, 0x50, 0xd3, 0x60, 0x30, 0x88, 0x01,
	0x75, 0x82, 0x21, 0xdb, 0xb2, 0x3d, 0x6e, 0x45, 0xf3, 0x35, 0x37, 0xd8, 0x96, 0x16, 0x72, 0xb2,
	0xb7, 0x3d, 0xa8, 0x36, 0xeb, 0xa8, 0x71, 0x24, 0x55, 0xa4, 0x57, 0x18, 0x28, 0xf6, 0x6f, 0xec,
	0xdf, 0xdc, 0xf3, 0x9e, 0x06, 0x52, 0x94, 0x44, 0x2a, 0xb2, 0x93, 0xaa, 0xed, 0x1b, 0x8f, 0x3c,
	0xde, 0xc7, 0xef, 0x7e, 0x77, 0x94, 0x60, 0x83, 0x5d, 0x85, 0xd1, 0x6c, 0x3f, 0x49, 0x63, 0x16,
	0x23, 0x10, 0x82, 0x58, 0xe3, 0x7f, 0x4c, 0x68, 0x1f, 0x5f, 0x05, 0x51, 0x44, 0xe6, 0xe8, 0x01,
	0x98, 0xe1, 0xd4, 0x33, 0x06, 0xc6, 0xb0, 0xeb, 0x9b, 0xe1, 0x14, 0xf5, 0xa0, 0x25, 0x34, 0x3d,
	0x53, 0x6c, 0x65, 0x02, 0x42, 0x60, 0x47, 0xc1, 0x0d, 0xf1, 0x2c, 0xb1, 0x29, 0xd6, 0xe8, 0x2b,
	0x80, 0x57, 0xf3, 0x38, 0x60, 0x7f, 0x04, 0xf3, 0x05, 0xf1, 0xec, 0x81, 0x31, 0x34, 0x7c, 0x65,
	0x07, 0x0d, 0x60, 0x83, 0xb2, 0x34, 0x8c, 0x66, 0x99, 0x42, 0x4b, 0x5c, 0x55, 0xb7, 0xd0, 0x0e,
	0x74, 0x5f, 0xc6, 0xf1, 0x3c, 0x3b, 0x77, 0x06, 0xc6, 0xb0, 0xe3, 0x97, 0x1b, 0xfc, 0x74, 0x1a,
	0xb0, 0x20, 0x3b, 0x6d, 0x8b, 0xdb, 0xe5, 0x06, 0xfa, 0x1a, 0xec, 0x45, 0x14, 0x32, 0xaf, 0x33,
	0x30, 0x86, 0x0f, 0x0e, 0xdc, 0xfd, 0x32, 0xbd, 0xfd, 0xcb, 0x28, 0x64, 0xbe, 0x38, 0xe5, 0x71,
	0xb3, 0x65, 0x42, 0xbc, 0xee, 0xc0, 0x18, 0xb6, 0x7c, 0xb1, 0x46, 0xdb, 0xd0, 0x09, 0xe9, 0x98,
	0x44, 0x34, 0x4e, 0x3d, 0x10, 0x4e, 0x0b, 0x19, 0xff, 0x6b, 0x40, 0xeb, 0x42, 0x64, 0x5c, 0xc5,
	0xa5, 0x0f, 0x0e, 0x25, 0x93, 0x94, 0x30, 0x09, 0x8c, 0x94, 0x90, 0x07, 0xed, 0x24, 0x8d, 0x5f,
	0x93, 0x09, 0x93, 0xe0, 0xe4, 0x62, 0x81, 0x99, 0xad, 0x60, 0xf6, 0x2d, 0x74, 0x26, 0x19, 0xf0,
	0xd4, 0x6b, 0x0d, 0xac, 0xe1, 0xc6, 0xc1, 0xa6, 0x1a, 0xb9, 0x2c, 0x8a, 0x5f, 0x28, 0x15, 0x09,
	0x38, 0x4a, 0x02, 0x7d, 0x70, 0x26, 0x71, 0xf4, 0x2a, 0x9c, 0x49, 0x54, 0xa4, 0xc4, 0x4b, 0x37,
	0x4b, 0xe3, 0x45, 0x22, 0x30, 0xe9, 0xfa, 0x99, 0xc0, 0xcb, 0x94, 0x5c, 0x2d, 0x69, 0x38, 0x09,
	0xe6, 0x67, 0x53, 0x01, 0x44, 0xd7, 0x57, 0x76, 0xf0, 0x7f, 0x06, 0x38, 0x63, 0x92, 0x86, 0x84,
	0x96, 0xb5, 0x37, 0xd4, 0xda, 0x7b, 0xd0, 0x96, 0xe1, 0xc8, 0xd4, 0x73, 0xb1, 0xc2, 0x00, 0xeb,
	0x2e, 0x06, 0xd8, 0x77, 0x30, 0xa0, 0xb5, 0x96, 0x01, 0xce, 0x2a, 0x06, 0xb4, 0xd7, 0x32, 0x60,
	0x07, 0xba, 0x2c, 0xbc, 0x21, 0x63, 0x16, 0xdc, 0xe4, 0xc0, 0x94, 0x1b, 0xf8, 0x67, 0x40, 0xc7,
	0x29, 0x09, 0x18, 0x11, 0x45, 0xf7, 0xc9, 0x9b, 0x05, 0xa1, 0x0c, 0x3d, 0x56, 0x71, 0xd8, 0x38,
	0xf8, 0x52, 0x35, 0x9d, 0x29, 0x66, 0xe7, 0xf8, 0x0d, 0x6c, 0x6a, 0xd7, 0x69, 0x12, 0x47, 0x94,
	0x70, 0xc4, 0xe8, 0x62, 0x32, 0x21, 0x94, 0x0a, 0x0b, 0x1d, 0x3f, 0x17, 0x39, 0xc2, 0x24, 0x4d,
	0xe3, 0x34, 0xef, 0x2e, 0x21, 0x48, 0xae, 0x59, 0x05, 0xd7, 0xb6, 0x15, 0x96, 0xd8, 0x03, 0x6b,
	0xd8, 0x2d, 0x09, 0x81, 0x9f, 0x80, 0x2b, 0x9c, 0x8d, 0x59, 0x7a, 0x9c, 0x93, 0xa4, 0xca, 0x55,
	0xf5, 0xbe, 0x59, 0xb9, 0xff, 0x54, 0x0b, 0x99, 0xe6, 0x29, 0xef, 0x82, 0x23, 0x52, 0xe2, 0x11,
	0x5b, 0xf5, 0x39, 0x4b, 0x05, 0xfc, 0x0e, 0x7a, 0xba, 0x85, 0x86, 0x59, 0xff, 0x58, 0xb8, 0xb4,
	0x84, 0xcb, 0x9d, 0x5b, 0x2e, 0x95, 0x1c, 0x0b, 0xef, 0x8f, 0xe1, 0x8b, 0x11, 0x61, 0x5a, 0xb9,
	0x6a, 0x69, 0x8b, 0xaf, 0xc1, 0x2d, 0x15, 0x1b, 0x86, 0x58, 0x10, 0xc1, 0xba, 0x83, 0x08, 0xaf,
	0x01, 0x5d, 0x26, 0xd3, 0x2a, 0x8f, 0xea, 0xfb, 0xa9, 0x07, 0xad, 0xf8, 0x6d, 0x44, 0x0a, 0x57,
	0x42, 0xa8, 0x9d, 0xb0, 0x45, 0x43, 0xdb, 0x4a, 0x43, 0xe3, 0x53, 0xd8, 0xd4, 0x7c, 0x35, 0xcb,
	0x0d, 0x7f, 0x07, 0xbd, 0x17, 0xd9, 0xa4, 0xd2, 0x99, 0xa0, 0x0c, 0x34, 0x43, 0x1b, 0x68, 0x38,
	0x85, 0xad, 0xca, 0x8d, 0x86, 0xb0, 0xee, 0x56, 0x2a, 0xbf, 0x86, 0x6c, 0xbf, 0xc2, 0x43, 0xe9,
	0x73, 0xc4, 0x93, 0xbf, 0x67, 0xa8, 0x25, 0x72, 0xa6, 0x8a, 0xdc, 0x5b, 0xd8, 0xae, 0x33, 0xf6,
	0xe9, 0xb3, 0x28, 0xb1, 0x3e, 0x21, 0x73, 0xc2, 0xc8, 0xdd, 0x58, 0x8f, 0x0a, 0xac, 0xf3, 0x1b,
	0x0d, 0xcb, 0xbc, 0x07, 0x28, 0xb3, 0x70, 0x8f, 0x96, 0x39, 0x85, 0x4d, 0x4d, 0xb7, 0xa1, 0xcb,
	0x04, 0x3e, 0x17, 0x06, 0x56, 0xce, 0x27, 0xfd, 0x49, 0x32, 0xab, 0x4f, 0x92, 0xf6, 0x4a, 0x5a,
	0xf7, 0x78, 0x25, 0x31, 0x03, 0x2f, 0x6b, 0x09, 0x79, 0x74, 0x1e, 0xdc, 0x90, 0xf5, 0x4d, 0xb8,
	0xfa, 0x51, 0x5b, 0xd1, 0x88, 0x59, 0xcb, 0xda, 0x4a, 0xcb, 0x72, 0x6e, 0xd6, 0x78, 0x6d, 0x08,
	0xda, 0xdf, 0xb0, 0xa5, 0x19, 0xa3, 0xeb, 0xe3, 0xff, 0xe8, 0x10, 0x3e, 0x83, 0x7e, 0xd5, 0x7f,
	0xc3, 0x4c, 0x5e, 0xc0, 0x23, 0x65, 0x3e, 0xd1, 0x6a, 0x3e, 0xdf, 0x57, 0x5e, 0x9a, 0x87, 0xb7,
	0xda, 0xe6, 0xd6, 0xcc, 0x3f, 0x07, 0xc7, 0x27, 0x74, 0x31, 0x5f, 0x53, 0xcc, 0x3c, 0x42, 0x73,
	0x45, 0x84, 0x96, 0x1a, 0xe1, 0x3b, 0xd8, 0xa9, 0x8f, 0x50, 0x66, 0xfc, 0x0d, 0xb4, 0x53, 0xe1,
	0x2f, 0x8f, 0x11, 0xa9, 0x31, 0x66, 0xa1, 0xf8, 0xb9, 0xca, 0x7b, 0x7b, 0xff, 0x05, 0xb6, 0x47,
	0x24, 0x22, 0x69, 0xc0, 0xc8, 0x21, 0xa5, 0xe1, 0x2c, 0xd2, 0x3a, 0xb3, 0xda, 0x2b, 0xca, 0x88,
	0x30, 0xf5, 0x11, 0x31, 0x81, 0x47, 0xb5, 0x76, 0x1a, 0x8e, 0x33, 0x0e, 0x6d, 0x7c, 0x4d, 0xa2,
	0x3c, 0x58, 0x21, 0xe0, 0x9f, 0x00, 0xd5, 0x04, 0x59, 0xe8, 0x1a, 0x8a, 0x2e, 0x72, 0xc1, 0xba,
	0x26, 0x4b, 0x69, 0x95, 0x2f, 0xf9, 0x40, 0xf9, 0x08, 0xa1, 0xe1, 0xa7, 0xd0, 0x3b, 0x21, 0xc1,
	0x87, 0x60, 0x35, 0x82, 0xad, 0x8a, 0x85, 0x86, 0xa1, 0x3c, 0x01, 0x94, 0x7d, 0x9a, 0x88, 0x2f,
	0xe6, 0x35, 0x81, 0xd4, 0x4f, 0x17, 0xfe, 0xc5, 0xa8, 0xdd, 0x6f, 0x58, 0xac, 0x3d, 0x70, 0xfe,
	0xe2, 0x1f, 0xc1, 0x79, 0x73, 0x6b, 0x04, 0x95, 0xb6, 0xa5, 0x06, 0xde, 0x85, 0xad, 0xfc, 0x43,
	0x88, 0x1e, 0x2d, 0xcf, 0x4e, 0x8a, 0xa8, 0x5d, 0xb0, 0xc2, 0x69, 0x46, 0xf1, 0xae, 0xcf, 0x97,
	0x98, 0x42, 0xbf, 0xaa, 0xfa, 0xe9, 0x1f, 0xc7, 0x67, 0xf9, 0xf0, 0xce, 0x9a, 0x5f, 0xfc, 0xcb,
	0xac, 0x1f, 0x7e, 0xe5, 0x0f, 0x90, 0xa9, 0xfe, 0x00, 0x95, 0x03, 0x59, 0xb3, 0xd4, 0xb0, 0xd2,
	0x7d, 0xe8, 0xe5, 0x58, 0x5c, 0x2c, 0x93, 0xa2, 0xd6, 0xf8, 0xcf, 0x12, 0x4e, 0xb9, 0xff, 0x01,
	0x0d, 0xc7, 0x0d, 0x08, 0x84, 0x78, 0x6e, 0x5c, 0xd8, 0x3b, 0x00, 0x9b, 0xff, 0xbd, 0xa0, 0x0e,
	0xd8, 0x47, 0xcf, 0x9f, 0xff, 0xe6, 0x7e, 0x86, 0x00, 0x9c, 0xf3, 0xcb, 0xdf, 0x8f, 0x4e, 0x7d,
	0xd7, 0xe0, 0xeb, 0xf1, 0x85, 0x7f, 0x76, 0x3e, 0x72, 0x4d, 0xae, 0x71, 0x72, 0x78, 0x71, 0xe8,
	0x5a, 0x2f, 0x1d, 0x01, 0xeb, 0x0f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x56, 0x28, 0x6c, 0x0e,
	0xf1, 0x0f, 0x00, 0x00,
}
