// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thing.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit int32

const (
	Unit_BOOL   Unit = 0
	Unit_NUMBER Unit = 1
	Unit_STRING Unit = 2
	Unit_DATA   Unit = 3
)

var Unit_name = map[int32]string{
	0: "BOOL",
	1: "NUMBER",
	2: "STRING",
	3: "DATA",
}

var Unit_value = map[string]int32{
	"BOOL":   0,
	"NUMBER": 1,
	"STRING": 2,
	"DATA":   3,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

type Channel struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string   `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            bool     `protobuf:"varint,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,8,opt,name=unit,proto3,enum=proto.Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ChannelFromBytes(data []byte) (*Channel, error) {
	t := &Channel{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Channel) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Channel) Reset()                   { *m = Channel{} }
func (m *Channel) String() string           { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()              {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() bool {
	if m != nil {
		return m.DataValue
	}
	return false
}

func (m *Channel) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

type Thing struct {
	// @inject_tag: bson:"_id"
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Project              string     `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Channels             []*Channel `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func ThingFromBytes(data []byte) (*Thing, error) {
	t := &Thing{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Thing) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Thing) Reset()                   { *m = Thing{} }
func (m *Thing) String() string           { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()              {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{1}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type CreateThingRequest struct {
	Thing                *Thing   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateThingRequestFromBytes(data []byte) (*CreateThingRequest, error) {
	t := &CreateThingRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateThingRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateThingRequest) Reset()                   { *m = CreateThingRequest{} }
func (m *CreateThingRequest) String() string           { return proto.CompactTextString(m) }
func (*CreateThingRequest) ProtoMessage()              {}
func (*CreateThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{2}
}

func (m *CreateThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingRequest.Unmarshal(m, b)
}
func (m *CreateThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingRequest.Marshal(b, m, deterministic)
}
func (m *CreateThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingRequest.Merge(m, src)
}
func (m *CreateThingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThingRequest.Size(m)
}
func (m *CreateThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingRequest proto.InternalMessageInfo

func (m *CreateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type CreateThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateThingResponseFromBytes(data []byte) (*CreateThingResponse, error) {
	t := &CreateThingResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateThingResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateThingResponse) Reset()                   { *m = CreateThingResponse{} }
func (m *CreateThingResponse) String() string           { return proto.CompactTextString(m) }
func (*CreateThingResponse) ProtoMessage()              {}
func (*CreateThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{3}
}

func (m *CreateThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingResponse.Unmarshal(m, b)
}
func (m *CreateThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingResponse.Marshal(b, m, deterministic)
}
func (m *CreateThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingResponse.Merge(m, src)
}
func (m *CreateThingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateThingResponse.Size(m)
}
func (m *CreateThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingResponse proto.InternalMessageInfo

func (m *CreateThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateThingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectThingsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectThingsRequestFromBytes(data []byte) (*ProjectThingsRequest, error) {
	t := &ProjectThingsRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectThingsRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectThingsRequest) Reset()                   { *m = ProjectThingsRequest{} }
func (m *ProjectThingsRequest) String() string           { return proto.CompactTextString(m) }
func (*ProjectThingsRequest) ProtoMessage()              {}
func (*ProjectThingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{4}
}

func (m *ProjectThingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsRequest.Unmarshal(m, b)
}
func (m *ProjectThingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsRequest.Marshal(b, m, deterministic)
}
func (m *ProjectThingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsRequest.Merge(m, src)
}
func (m *ProjectThingsRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsRequest.Size(m)
}
func (m *ProjectThingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsRequest proto.InternalMessageInfo

func (m *ProjectThingsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectThingsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Things               []*Thing `protobuf:"bytes,3,rep,name=things,proto3" json:"things,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectThingsResponseFromBytes(data []byte) (*ProjectThingsResponse, error) {
	t := &ProjectThingsResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectThingsResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectThingsResponse) Reset()                   { *m = ProjectThingsResponse{} }
func (m *ProjectThingsResponse) String() string           { return proto.CompactTextString(m) }
func (*ProjectThingsResponse) ProtoMessage()              {}
func (*ProjectThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65361fd47d76e14b, []int{5}
}

func (m *ProjectThingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectThingsResponse.Unmarshal(m, b)
}
func (m *ProjectThingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectThingsResponse.Marshal(b, m, deterministic)
}
func (m *ProjectThingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectThingsResponse.Merge(m, src)
}
func (m *ProjectThingsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectThingsResponse.Size(m)
}
func (m *ProjectThingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectThingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectThingsResponse proto.InternalMessageInfo

func (m *ProjectThingsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectThingsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Unit", Unit_name, Unit_value)
	proto.RegisterType((*Channel)(nil), "proto.Channel")
	proto.RegisterType((*Thing)(nil), "proto.Thing")
	proto.RegisterType((*CreateThingRequest)(nil), "proto.CreateThingRequest")
	proto.RegisterType((*CreateThingResponse)(nil), "proto.CreateThingResponse")
	proto.RegisterType((*ProjectThingsRequest)(nil), "proto.ProjectThingsRequest")
	proto.RegisterType((*ProjectThingsResponse)(nil), "proto.ProjectThingsResponse")
}

func init() { proto.RegisterFile("thing.proto", fileDescriptor_65361fd47d76e14b) }

var fileDescriptor_65361fd47d76e14b = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xcf, 0x6f, 0xda, 0x30,
	0x14, 0x9e, 0xf3, 0x8b, 0xf0, 0x32, 0xa1, 0xc8, 0x63, 0x92, 0x0f, 0xd3, 0x16, 0x45, 0x3b, 0x44,
	0x1c, 0xd0, 0x94, 0x5d, 0x76, 0x05, 0x36, 0x4d, 0x95, 0x5a, 0xa8, 0x5c, 0xe8, 0x3d, 0x04, 0x17,
	0x52, 0x05, 0x1b, 0x62, 0xe7, 0x1f, 0xee, 0x5f, 0x52, 0xc5, 0x4e, 0x28, 0xa0, 0x9e, 0x7a, 0xb2,
	0xdf, 0xf7, 0xbd, 0xcf, 0x7e, 0xdf, 0xf7, 0x20, 0x50, 0xbb, 0x82, 0x6f, 0xc7, 0x87, 0x4a, 0x28,
	0x81, 0x5d, 0x7d, 0xc4, 0x2f, 0x08, 0x7a, 0xb3, 0x5d, 0xc6, 0x39, 0x2b, 0xf1, 0x00, 0xac, 0x62,
	0x43, 0x50, 0x84, 0x92, 0x3e, 0xb5, 0x8a, 0x0d, 0x1e, 0x82, 0xab, 0x15, 0xc4, 0xd2, 0x90, 0x29,
	0x30, 0x06, 0x87, 0x67, 0x7b, 0x46, 0x6c, 0x0d, 0xea, 0x3b, 0xfe, 0x0e, 0xf0, 0x54, 0x8a, 0x4c,
	0x3d, 0x66, 0x65, 0xcd, 0x88, 0x13, 0xa1, 0x04, 0xd1, 0x33, 0x04, 0x47, 0x10, 0x48, 0x55, 0x15,
	0x7c, 0x6b, 0x1a, 0x5c, 0x2d, 0x3d, 0x87, 0xf0, 0x37, 0xe8, 0xaf, 0x85, 0x28, 0x0d, 0xef, 0x45,
	0x28, 0xf1, 0xe9, 0x1b, 0xd0, 0xb0, 0x9b, 0x4c, 0x65, 0x86, 0xed, 0x19, 0xf6, 0x04, 0xe0, 0x1f,
	0xe0, 0xd4, 0xbc, 0x50, 0xc4, 0x8f, 0x50, 0x32, 0x48, 0x03, 0x63, 0x70, 0xbc, 0xe2, 0x85, 0xa2,
	0x9a, 0x88, 0x8f, 0xe0, 0x2e, 0xf5, 0xec, 0xd7, 0x0e, 0x09, 0xf4, 0x0e, 0x95, 0x78, 0x66, 0xb9,
	0x6a, 0x3d, 0x76, 0xe5, 0xbb, 0x2e, 0x47, 0xe0, 0xe7, 0x26, 0x2a, 0x49, 0x9c, 0xc8, 0x4e, 0x82,
	0x74, 0xd0, 0xfe, 0xd5, 0x26, 0x48, 0x4f, 0x7c, 0xfc, 0x07, 0xf0, 0xac, 0x62, 0x99, 0x62, 0xfa,
	0x63, 0xca, 0x8e, 0x35, 0x93, 0x0a, 0xc7, 0x5d, 0xa2, 0xcd, 0x08, 0x41, 0xfa, 0xb9, 0x95, 0x9b,
	0x1e, 0x43, 0xc5, 0x2b, 0xf8, 0x72, 0xa1, 0x94, 0x07, 0xc1, 0x25, 0x6b, 0x46, 0x95, 0x75, 0x9e,
	0x33, 0x29, 0xb5, 0xd8, 0xa7, 0x5d, 0xd9, 0xac, 0x89, 0x55, 0x95, 0xa8, 0xba, 0x35, 0xe9, 0xa2,
	0xb5, 0x6a, 0x77, 0x56, 0xe3, 0x5f, 0x30, 0xbc, 0x37, 0xde, 0xf4, 0xbb, 0xb2, 0x1b, 0xe9, 0x2c,
	0x02, 0x74, 0x11, 0x41, 0xbc, 0x87, 0xaf, 0x57, 0x8a, 0x0f, 0x8e, 0xf2, 0x13, 0x3c, 0x6d, 0x4d,
	0x12, 0x5b, 0xa7, 0x76, 0x69, 0xbb, 0xe5, 0x46, 0x29, 0x38, 0xcd, 0xca, 0xb0, 0x0f, 0xce, 0x74,
	0xb1, 0xb8, 0x0d, 0x3f, 0x61, 0x00, 0x6f, 0xbe, 0xba, 0x9b, 0xfe, 0xa3, 0x21, 0x6a, 0xee, 0x0f,
	0x4b, 0x7a, 0x33, 0xff, 0x1f, 0x5a, 0x4d, 0xc7, 0xdf, 0xc9, 0x72, 0x12, 0xda, 0x6b, 0x4f, 0x3f,
	0xf4, 0xfb, 0x35, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xd1, 0x6a, 0xd6, 0xda, 0x02, 0x00, 0x00,
}
