// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package appproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit int32

const (
	Unit_BOOL   Unit = 0
	Unit_NUMBER Unit = 1
	Unit_STRING Unit = 2
	Unit_DATA   Unit = 3
)

var Unit_name = map[int32]string{
	0: "BOOL",
	1: "NUMBER",
	2: "STRING",
	3: "DATA",
}

var Unit_value = map[string]int32{
	"BOOL":   0,
	"NUMBER": 1,
	"STRING": 2,
	"DATA":   3,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}

func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

type Channel struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Thing                string   `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 Unit     `protobuf:"varint,8,opt,name=unit,proto3,enum=appproto.Unit" json:"unit,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	IsSensor             bool     `protobuf:"varint,10,opt,name=isSensor,proto3" json:"isSensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ChannelFromBytes(data []byte) (*Channel, error) {
	t := &Channel{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Channel) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Channel) Reset()                   { *m = Channel{} }
func (m *Channel) String() string           { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()              {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_BOOL
}

func (m *Channel) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Channel) GetIsSensor() bool {
	if m != nil {
		return m.IsSensor
	}
	return false
}

type ThingUpdate struct {
	Thing                string     `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Channels             []*Channel `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func ThingUpdateFromBytes(data []byte) (*ThingUpdate, error) {
	t := &ThingUpdate{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ThingUpdate) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ThingUpdate) Reset()                   { *m = ThingUpdate{} }
func (m *ThingUpdate) String() string           { return proto.CompactTextString(m) }
func (*ThingUpdate) ProtoMessage()              {}
func (*ThingUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *ThingUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingUpdate.Unmarshal(m, b)
}
func (m *ThingUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingUpdate.Marshal(b, m, deterministic)
}
func (m *ThingUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingUpdate.Merge(m, src)
}
func (m *ThingUpdate) XXX_Size() int {
	return xxx_messageInfo_ThingUpdate.Size(m)
}
func (m *ThingUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ThingUpdate proto.InternalMessageInfo

func (m *ThingUpdate) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *ThingUpdate) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type SendThingUpdateRequest struct {
	Update               *ThingUpdate `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func SendThingUpdateRequestFromBytes(data []byte) (*SendThingUpdateRequest, error) {
	t := &SendThingUpdateRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *SendThingUpdateRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *SendThingUpdateRequest) Reset()                   { *m = SendThingUpdateRequest{} }
func (m *SendThingUpdateRequest) String() string           { return proto.CompactTextString(m) }
func (*SendThingUpdateRequest) ProtoMessage()              {}
func (*SendThingUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *SendThingUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendThingUpdateRequest.Unmarshal(m, b)
}
func (m *SendThingUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendThingUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SendThingUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendThingUpdateRequest.Merge(m, src)
}
func (m *SendThingUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SendThingUpdateRequest.Size(m)
}
func (m *SendThingUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendThingUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendThingUpdateRequest proto.InternalMessageInfo

func (m *SendThingUpdateRequest) GetUpdate() *ThingUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

type SendThingUpdateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func SendThingUpdateResponseFromBytes(data []byte) (*SendThingUpdateResponse, error) {
	t := &SendThingUpdateResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *SendThingUpdateResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *SendThingUpdateResponse) Reset()                   { *m = SendThingUpdateResponse{} }
func (m *SendThingUpdateResponse) String() string           { return proto.CompactTextString(m) }
func (*SendThingUpdateResponse) ProtoMessage()              {}
func (*SendThingUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *SendThingUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendThingUpdateResponse.Unmarshal(m, b)
}
func (m *SendThingUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendThingUpdateResponse.Marshal(b, m, deterministic)
}
func (m *SendThingUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendThingUpdateResponse.Merge(m, src)
}
func (m *SendThingUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_SendThingUpdateResponse.Size(m)
}
func (m *SendThingUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendThingUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendThingUpdateResponse proto.InternalMessageInfo

func (m *SendThingUpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendThingUpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("appproto.Unit", Unit_name, Unit_value)
	proto.RegisterType((*Channel)(nil), "appproto.Channel")
	proto.RegisterType((*ThingUpdate)(nil), "appproto.ThingUpdate")
	proto.RegisterType((*SendThingUpdateRequest)(nil), "appproto.SendThingUpdateRequest")
	proto.RegisterType((*SendThingUpdateResponse)(nil), "appproto.SendThingUpdateResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x5d, 0x6b, 0xea, 0x30,
	0x18, 0x3e, 0xa9, 0xb5, 0xb6, 0x6f, 0x41, 0x7a, 0xc2, 0xf9, 0x08, 0x87, 0xc3, 0x28, 0xbd, 0x2a,
	0x03, 0xbd, 0xe8, 0x7e, 0x81, 0x6e, 0x43, 0x84, 0x4d, 0x21, 0xea, 0xee, 0xa3, 0xcd, 0xb4, 0xd0,
	0x25, 0x59, 0x93, 0x5e, 0xec, 0x87, 0xec, 0xff, 0x8e, 0xa6, 0x6a, 0x0b, 0xbb, 0x7b, 0x9f, 0x8f,
	0x3c, 0xc9, 0xfb, 0x04, 0x02, 0xa6, 0xd4, 0x54, 0x55, 0xd2, 0x48, 0xec, 0x33, 0xa5, 0xec, 0x94,
	0x7c, 0x3a, 0x30, 0xba, 0x3f, 0x31, 0x21, 0x78, 0x89, 0xc7, 0xe0, 0x14, 0x39, 0x41, 0x31, 0x4a,
	0x03, 0xea, 0x14, 0x39, 0xfe, 0x05, 0x43, 0x73, 0x2a, 0xc4, 0x91, 0x38, 0x96, 0x6a, 0x01, 0xc6,
	0xe0, 0x0a, 0xf6, 0xc6, 0xc9, 0xc0, 0x92, 0x76, 0xc6, 0x37, 0x00, 0xaf, 0xa5, 0x64, 0xe6, 0x85,
	0x95, 0x35, 0x27, 0x6e, 0x8c, 0x52, 0x44, 0x7b, 0x0c, 0x8e, 0x21, 0xd4, 0xa6, 0x2a, 0xc4, 0xb1,
	0x35, 0x0c, 0xed, 0xd1, 0x3e, 0x85, 0xff, 0x43, 0xb0, 0x97, 0xb2, 0x6c, 0x75, 0x2f, 0x46, 0xa9,
	0x4f, 0x3b, 0xa2, 0x51, 0x73, 0x66, 0x58, 0xab, 0x8e, 0xec, 0xe9, 0x8e, 0xc0, 0x09, 0xb8, 0xb5,
	0x28, 0x0c, 0xf1, 0x63, 0x94, 0x8e, 0xb3, 0xf1, 0xf4, 0xb2, 0xdc, 0x74, 0x27, 0x0a, 0x43, 0xad,
	0xd6, 0xbc, 0xda, 0x7c, 0x28, 0x4e, 0x82, 0x18, 0xa5, 0x43, 0x6a, 0x67, 0xfc, 0x0f, 0xfc, 0x42,
	0x6f, 0xb8, 0xd0, 0xb2, 0x22, 0x60, 0xaf, 0xbc, 0xe2, 0x84, 0x42, 0xb8, 0x6d, 0xd6, 0xdd, 0xa9,
	0x9c, 0x19, 0xde, 0x55, 0x81, 0xfa, 0x55, 0x4c, 0xc0, 0x3f, 0xb4, 0xdd, 0x69, 0xe2, 0xc4, 0x83,
	0x34, 0xcc, 0x7e, 0x76, 0x97, 0x9f, 0x5b, 0xa5, 0x57, 0x4b, 0xb2, 0x80, 0x3f, 0x1b, 0x2e, 0xf2,
	0x5e, 0x2e, 0xe5, 0xef, 0x35, 0xd7, 0x06, 0x4f, 0xc0, 0xab, 0x2d, 0x61, 0xf3, 0xc3, 0xec, 0x77,
	0x17, 0xd3, 0x77, 0x9f, 0x4d, 0xc9, 0x12, 0xfe, 0x7e, 0x0b, 0xd2, 0x4a, 0x0a, 0xcd, 0x31, 0x81,
	0x91, 0xae, 0x0f, 0x07, 0xae, 0xb5, 0x8d, 0xf2, 0xe9, 0x05, 0x36, 0x2b, 0xf0, 0xaa, 0x92, 0xd5,
	0xe5, 0x37, 0x2d, 0xb8, 0xcd, 0xc0, 0x6d, 0x5a, 0xc2, 0x3e, 0xb8, 0xf3, 0xf5, 0xfa, 0x29, 0xfa,
	0x81, 0x01, 0xbc, 0xd5, 0xee, 0x79, 0xfe, 0x48, 0x23, 0xd4, 0xcc, 0x9b, 0x2d, 0x5d, 0xae, 0x16,
	0x91, 0xd3, 0x38, 0x1e, 0x66, 0xdb, 0x59, 0x34, 0xd8, 0x7b, 0xf6, 0x65, 0x77, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x47, 0x41, 0x00, 0x60, 0x51, 0x02, 0x00, 0x00,
}
