// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type VerifyUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserRequest) Reset()         { *m = VerifyUserRequest{} }
func (m *VerifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRequest) ProtoMessage()    {}
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *VerifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRequest.Unmarshal(m, b)
}
func (m *VerifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRequest.Marshal(b, m, deterministic)
}
func (m *VerifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRequest.Merge(m, src)
}
func (m *VerifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRequest.Size(m)
}
func (m *VerifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRequest proto.InternalMessageInfo

func (m *VerifyUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserResponse) Reset()         { *m = VerifyUserResponse{} }
func (m *VerifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUserResponse) ProtoMessage()    {}
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *VerifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserResponse.Unmarshal(m, b)
}
func (m *VerifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserResponse.Marshal(b, m, deterministic)
}
func (m *VerifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserResponse.Merge(m, src)
}
func (m *VerifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyUserResponse.Size(m)
}
func (m *VerifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserResponse proto.InternalMessageInfo

func (m *VerifyUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *VerifyUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *VerifyUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "userproto.User")
	proto.RegisterType((*CreateUserRequest)(nil), "userproto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "userproto.CreateUserResponse")
	proto.RegisterType((*VerifyUserRequest)(nil), "userproto.VerifyUserRequest")
	proto.RegisterType((*VerifyUserResponse)(nil), "userproto.VerifyUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x31, 0x4f, 0xc4, 0x30,
	0x0c, 0x85, 0xd5, 0x34, 0xc0, 0x9d, 0x91, 0x40, 0x67, 0x31, 0x44, 0x4c, 0x28, 0x2c, 0x4c, 0x1d,
	0x60, 0x61, 0x47, 0xfc, 0x81, 0x0a, 0x98, 0x58, 0xc2, 0xd5, 0x48, 0x91, 0xb8, 0x4b, 0xb1, 0x5b,
	0x21, 0xfe, 0x3d, 0x8a, 0xa1, 0x51, 0xc4, 0xc0, 0xc0, 0xe6, 0xf7, 0x5a, 0xe7, 0xbd, 0xcf, 0x00,
	0xb3, 0x10, 0x77, 0x23, 0xa7, 0x29, 0xe1, 0x3a, 0xcf, 0x3a, 0xfa, 0x67, 0xb0, 0x8f, 0x42, 0x8c,
	0x27, 0x60, 0xe2, 0xe0, 0x9a, 0x8b, 0xe6, 0x6a, 0xdd, 0x9b, 0x38, 0xe0, 0x19, 0x1c, 0xd0, 0x2e,
	0xc4, 0x37, 0x67, 0xd4, 0xfa, 0x16, 0x88, 0x60, 0xf7, 0x61, 0x47, 0xae, 0x55, 0x53, 0x67, 0x3c,
	0x87, 0xd5, 0x18, 0x44, 0x3e, 0x12, 0x0f, 0xce, 0xaa, 0x5f, 0xb4, 0xbf, 0x85, 0xcd, 0x1d, 0x53,
	0x98, 0x28, 0x67, 0xf4, 0xf4, 0x3e, 0x93, 0x4c, 0x78, 0x09, 0x36, 0xe7, 0x6b, 0xd8, 0xf1, 0xf5,
	0x69, 0x57, 0xca, 0x74, 0xfa, 0x97, 0x7e, 0xf4, 0x0f, 0x80, 0xf5, 0xa6, 0x8c, 0x69, 0x2f, 0x84,
	0x0e, 0x8e, 0x64, 0xde, 0x6e, 0x49, 0x44, 0xb7, 0x57, 0xfd, 0x22, 0xb5, 0x2f, 0x73, 0xe2, 0xd2,
	0x37, 0x8b, 0x1f, 0xaa, 0x76, 0xa1, 0xf2, 0xf7, 0xb0, 0x79, 0x22, 0x8e, 0xaf, 0x9f, 0x75, 0x9f,
	0x82, 0xda, 0xd4, 0xa8, 0x35, 0x96, 0xf9, 0x85, 0x15, 0x01, 0xeb, 0x67, 0xfe, 0x59, 0x6e, 0xb9,
	0x43, 0xfb, 0xc7, 0x1d, 0x5e, 0x0e, 0xd5, 0xb9, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x4a,
	0x2e, 0x2e, 0xbf, 0x01, 0x00, 0x00,
}
