// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectFromBytes(data []byte) (*Project, error) {
	t := &Project{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Project) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Project) Reset()                   { *m = Project{} }
func (m *Project) String() string           { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()              {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateProjectRequestFromBytes(data []byte) (*CreateProjectRequest, error) {
	t := &CreateProjectRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateProjectRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateProjectRequest) Reset()                   { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string           { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()              {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{1}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CreateProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateProjectResponseFromBytes(data []byte) (*CreateProjectResponse, error) {
	t := &CreateProjectResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateProjectResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateProjectResponse) Reset()                   { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string           { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()              {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{2}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateProjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserProjectsRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func UserProjectsRequestFromBytes(data []byte) (*UserProjectsRequest, error) {
	t := &UserProjectsRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UserProjectsRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UserProjectsRequest) Reset()                   { *m = UserProjectsRequest{} }
func (m *UserProjectsRequest) String() string           { return proto.CompactTextString(m) }
func (*UserProjectsRequest) ProtoMessage()              {}
func (*UserProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{3}
}

func (m *UserProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProjectsRequest.Unmarshal(m, b)
}
func (m *UserProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProjectsRequest.Marshal(b, m, deterministic)
}
func (m *UserProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProjectsRequest.Merge(m, src)
}
func (m *UserProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_UserProjectsRequest.Size(m)
}
func (m *UserProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserProjectsRequest proto.InternalMessageInfo

func (m *UserProjectsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type UserProjectsResponse struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Projects             []*Project `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func UserProjectsResponseFromBytes(data []byte) (*UserProjectsResponse, error) {
	t := &UserProjectsResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UserProjectsResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UserProjectsResponse) Reset()                   { *m = UserProjectsResponse{} }
func (m *UserProjectsResponse) String() string           { return proto.CompactTextString(m) }
func (*UserProjectsResponse) ProtoMessage()              {}
func (*UserProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{4}
}

func (m *UserProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProjectsResponse.Unmarshal(m, b)
}
func (m *UserProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProjectsResponse.Marshal(b, m, deterministic)
}
func (m *UserProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProjectsResponse.Merge(m, src)
}
func (m *UserProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_UserProjectsResponse.Size(m)
}
func (m *UserProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserProjectsResponse proto.InternalMessageInfo

func (m *UserProjectsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserProjectsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UserProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GetProjectRequestFromBytes(data []byte) (*GetProjectRequest, error) {
	t := &GetProjectRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GetProjectRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GetProjectRequest) Reset()                   { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string           { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()              {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{5}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProjectRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Project              *Project `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func GetProjectResponseFromBytes(data []byte) (*GetProjectResponse, error) {
	t := &GetProjectResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *GetProjectResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *GetProjectResponse) Reset()                   { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string           { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()              {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{6}
}

func (m *GetProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectResponse.Unmarshal(m, b)
}
func (m *GetProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectResponse.Merge(m, src)
}
func (m *GetProjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectResponse.Size(m)
}
func (m *GetProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectResponse proto.InternalMessageInfo

func (m *GetProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteProjectRequestFromBytes(data []byte) (*DeleteProjectRequest, error) {
	t := &DeleteProjectRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteProjectRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteProjectRequest) Reset()                   { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string           { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()              {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{7}
}

func (m *DeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectRequest.Unmarshal(m, b)
}
func (m *DeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectRequest.Merge(m, src)
}
func (m *DeleteProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectRequest.Size(m)
}
func (m *DeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectRequest proto.InternalMessageInfo

func (m *DeleteProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteProjectRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeleteProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteProjectResponseFromBytes(data []byte) (*DeleteProjectResponse, error) {
	t := &DeleteProjectResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteProjectResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteProjectResponse) Reset()                   { *m = DeleteProjectResponse{} }
func (m *DeleteProjectResponse) String() string           { return proto.CompactTextString(m) }
func (*DeleteProjectResponse) ProtoMessage()              {}
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{8}
}

func (m *DeleteProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectResponse.Unmarshal(m, b)
}
func (m *DeleteProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectResponse.Merge(m, src)
}
func (m *DeleteProjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectResponse.Size(m)
}
func (m *DeleteProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectResponse proto.InternalMessageInfo

func (m *DeleteProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteProjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func UpdateProjectRequestFromBytes(data []byte) (*UpdateProjectRequest, error) {
	t := &UpdateProjectRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateProjectRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateProjectRequest) Reset()                   { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string           { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()              {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{9}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProjectRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateProjectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func UpdateProjectResponseFromBytes(data []byte) (*UpdateProjectResponse, error) {
	t := &UpdateProjectResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *UpdateProjectResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *UpdateProjectResponse) Reset()                   { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string           { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()              {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{10}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

func (m *UpdateProjectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateProjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Project)(nil), "proto.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "proto.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "proto.CreateProjectResponse")
	proto.RegisterType((*UserProjectsRequest)(nil), "proto.UserProjectsRequest")
	proto.RegisterType((*UserProjectsResponse)(nil), "proto.UserProjectsResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "proto.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "proto.GetProjectResponse")
	proto.RegisterType((*DeleteProjectRequest)(nil), "proto.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectResponse)(nil), "proto.DeleteProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "proto.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "proto.UpdateProjectResponse")
}

func init() { proto.RegisterFile("project.proto", fileDescriptor_8340e6318dfdfac2) }

var fileDescriptor_8340e6318dfdfac2 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0xbb, 0x6b, 0xd7, 0x59, 0x5c, 0x30, 0xb6, 0x90, 0x63, 0xc9, 0x69, 0x51, 0xd8,
	0x83, 0x9e, 0x04, 0x0f, 0x82, 0x42, 0xaf, 0x52, 0x10, 0xcf, 0xb5, 0x9d, 0x43, 0x45, 0x9b, 0x9a,
	0xc9, 0xe2, 0xdf, 0x17, 0xa7, 0x4d, 0xa9, 0x55, 0x96, 0x25, 0xa7, 0x76, 0x66, 0x92, 0x99, 0xef,
	0xcd, 0x0b, 0x9c, 0x75, 0x46, 0xbf, 0x61, 0x65, 0x77, 0x9d, 0xd1, 0x56, 0x8b, 0x25, 0x7f, 0x14,
	0x42, 0xfc, 0xd4, 0xe7, 0xc5, 0x06, 0xc2, 0xa6, 0x96, 0x41, 0x16, 0x6c, 0x4f, 0x8b, 0xb0, 0xa9,
	0x45, 0x02, 0x4b, 0xfd, 0xd5, 0xa2, 0x91, 0x21, 0xa7, 0xfa, 0x40, 0x08, 0x58, 0xb4, 0xe5, 0x07,
	0xca, 0x88, 0x93, 0xfc, 0x2f, 0x32, 0x58, 0xd7, 0x48, 0x95, 0x69, 0x3a, 0xdb, 0xe8, 0x56, 0x2e,
	0xb8, 0x34, 0x4d, 0xa9, 0x7b, 0x48, 0x1e, 0x0c, 0x96, 0x16, 0x87, 0x61, 0x05, 0x7e, 0xee, 0x91,
	0xac, 0xd8, 0x42, 0x3c, 0x60, 0xf1, 0xe0, 0xf5, 0xf5, 0xa6, 0xc7, 0xdb, 0xb9, 0x73, 0xae, 0xac,
	0x5e, 0x20, 0x9d, 0x75, 0xa0, 0x4e, 0xb7, 0x84, 0x42, 0x42, 0x4c, 0xfb, 0xaa, 0x42, 0x22, 0x6e,
	0xb1, 0x2a, 0x5c, 0xf8, 0x23, 0x00, 0x8d, 0xd1, 0xa3, 0x00, 0x0e, 0x06, 0x99, 0x91, 0x93, 0xa9,
	0xae, 0xe0, 0xe2, 0x99, 0xd0, 0x0c, 0x6d, 0xc9, 0x91, 0x8d, 0xea, 0x83, 0x89, 0x7a, 0x65, 0x20,
	0xf9, 0x7d, 0xd8, 0x13, 0xe2, 0x12, 0x56, 0x83, 0x30, 0x92, 0x51, 0x16, 0xfd, 0x23, 0x7c, 0xac,
	0xab, 0x5b, 0x38, 0xcf, 0xd1, 0xce, 0x16, 0x77, 0x94, 0x59, 0xaa, 0x05, 0x31, 0xbd, 0xea, 0x09,
	0x3b, 0x31, 0x29, 0x3a, 0x6c, 0xd2, 0x1d, 0x24, 0x8f, 0xf8, 0x8e, 0x7f, 0x6c, 0x3e, 0x8e, 0x36,
	0x87, 0x74, 0x76, 0xdb, 0x0f, 0x98, 0x5d, 0xea, 0xea, 0xd2, 0x0f, 0xc3, 0xf3, 0x85, 0xe7, 0x90,
	0xce, 0x66, 0xfa, 0xc1, 0xbf, 0x9e, 0xf0, 0x6e, 0x6f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9d,
	0xe7, 0xfa, 0x80, 0xb0, 0x03, 0x00, 0x00,
}
