// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rule.proto

package ruleproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_EQUAL            Operation = 0
	Operation_NOTEQUAL         Operation = 1
	Operation_LESSTHAN         Operation = 2
	Operation_LESSTHANEQUAL    Operation = 3
	Operation_GREATERTHAN      Operation = 4
	Operation_GREATERTHANEQUAL Operation = 5
	Operation_AND              Operation = 6
	Operation_OR               Operation = 7
)

var Operation_name = map[int32]string{
	0: "EQUAL",
	1: "NOTEQUAL",
	2: "LESSTHAN",
	3: "LESSTHANEQUAL",
	4: "GREATERTHAN",
	5: "GREATERTHANEQUAL",
	6: "AND",
	7: "OR",
}

var Operation_value = map[string]int32{
	"EQUAL":            0,
	"NOTEQUAL":         1,
	"LESSTHAN":         2,
	"LESSTHANEQUAL":    3,
	"GREATERTHAN":      4,
	"GREATERTHANEQUAL": 5,
	"AND":              6,
	"OR":               7,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{0}
}

type TriggerType int32

const (
	TriggerType_COMMAND TriggerType = 0
)

var TriggerType_name = map[int32]string{
	0: "COMMAND",
}

var TriggerType_value = map[string]int32{
	"COMMAND": 0,
}

func (x TriggerType) String() string {
	return proto.EnumName(TriggerType_name, int32(x))
}

func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{1}
}

type Channel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,2,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,3,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,4,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,5,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32    `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type TriggerCommand struct {
	Thing                string     `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	PhysicalId           string     `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []*Channel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TriggerCommand) Reset()         { *m = TriggerCommand{} }
func (m *TriggerCommand) String() string { return proto.CompactTextString(m) }
func (*TriggerCommand) ProtoMessage()    {}
func (*TriggerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{1}
}

func (m *TriggerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerCommand.Unmarshal(m, b)
}
func (m *TriggerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerCommand.Marshal(b, m, deterministic)
}
func (m *TriggerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerCommand.Merge(m, src)
}
func (m *TriggerCommand) XXX_Size() int {
	return xxx_messageInfo_TriggerCommand.Size(m)
}
func (m *TriggerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerCommand proto.InternalMessageInfo

func (m *TriggerCommand) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *TriggerCommand) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *TriggerCommand) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type ThingChLink struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingChLink) Reset()         { *m = ThingChLink{} }
func (m *ThingChLink) String() string { return proto.CompactTextString(m) }
func (*ThingChLink) ProtoMessage()    {}
func (*ThingChLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{2}
}

func (m *ThingChLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingChLink.Unmarshal(m, b)
}
func (m *ThingChLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingChLink.Marshal(b, m, deterministic)
}
func (m *ThingChLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingChLink.Merge(m, src)
}
func (m *ThingChLink) XXX_Size() int {
	return xxx_messageInfo_ThingChLink.Size(m)
}
func (m *ThingChLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingChLink.DiscardUnknown(m)
}

var xxx_messageInfo_ThingChLink proto.InternalMessageInfo

func (m *ThingChLink) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Rule struct {
	// @inject_tag: bson:"_id"
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string            `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Project              string            `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	FloatValue           float64           `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string            `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool              `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string            `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32             `protobuf:"varint,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Operation            Operation         `protobuf:"varint,9,opt,name=operation,proto3,enum=ruleproto.Operation" json:"operation,omitempty"`
	TriggerType          TriggerType       `protobuf:"varint,10,opt,name=triggerType,proto3,enum=ruleproto.TriggerType" json:"triggerType,omitempty"`
	TriggerCommands      []*TriggerCommand `protobuf:"bytes,11,rep,name=triggerCommands,proto3" json:"triggerCommands,omitempty"`
	Channel              string            `protobuf:"bytes,12,opt,name=channel,proto3" json:"channel,omitempty"`
	Val                  bool              `protobuf:"varint,13,opt,name=val,proto3" json:"val,omitempty"`
	Vals                 string            `protobuf:"bytes,14,opt,name=vals,proto3" json:"vals,omitempty"`
	Rules                []*Rule           `protobuf:"bytes,15,rep,name=rules,proto3" json:"rules,omitempty"`
	ThingChLink          *ThingChLink      `protobuf:"bytes,16,opt,name=thingChLink,proto3" json:"thingChLink,omitempty"`
	IsRoot               bool              `protobuf:"varint,17,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Uid                  string            `protobuf:"bytes,18,opt,name=uid,proto3" json:"uid,omitempty"`
	IsLeaf               bool              `protobuf:"varint,19,opt,name=isLeaf,proto3" json:"isLeaf,omitempty"`
	Root                 string            `protobuf:"bytes,20,opt,name=root,proto3" json:"root,omitempty"`
	PhysicalId           string            `protobuf:"bytes,21,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{3}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Rule) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Rule) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Rule) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Rule) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Rule) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Rule) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Rule) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *Rule) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_EQUAL
}

func (m *Rule) GetTriggerType() TriggerType {
	if m != nil {
		return m.TriggerType
	}
	return TriggerType_COMMAND
}

func (m *Rule) GetTriggerCommands() []*TriggerCommand {
	if m != nil {
		return m.TriggerCommands
	}
	return nil
}

func (m *Rule) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Rule) GetVal() bool {
	if m != nil {
		return m.Val
	}
	return false
}

func (m *Rule) GetVals() string {
	if m != nil {
		return m.Vals
	}
	return ""
}

func (m *Rule) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Rule) GetThingChLink() *ThingChLink {
	if m != nil {
		return m.ThingChLink
	}
	return nil
}

func (m *Rule) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *Rule) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Rule) GetIsLeaf() bool {
	if m != nil {
		return m.IsLeaf
	}
	return false
}

func (m *Rule) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Rule) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

type CreateRuleRequest struct {
	Rule                 *Rule    `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	ThingsMap            string   `protobuf:"bytes,2,opt,name=thingsMap,proto3" json:"thingsMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleRequest) Reset()         { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()    {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{4}
}

func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(m, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *CreateRuleRequest) GetThingsMap() string {
	if m != nil {
		return m.ThingsMap
	}
	return ""
}

type CreateRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleResponse) Reset()         { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()    {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{5}
}

func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(m, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

func (m *CreateRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRuleRequest struct {
	Rule                 string   `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleRequest) Reset()         { *m = DeleteRuleRequest{} }
func (m *DeleteRuleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleRequest) ProtoMessage()    {}
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{6}
}

func (m *DeleteRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleRequest.Unmarshal(m, b)
}
func (m *DeleteRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleRequest.Merge(m, src)
}
func (m *DeleteRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleRequest.Size(m)
}
func (m *DeleteRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleRequest proto.InternalMessageInfo

func (m *DeleteRuleRequest) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

type DeleteRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleResponse) Reset()         { *m = DeleteRuleResponse{} }
func (m *DeleteRuleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleResponse) ProtoMessage()    {}
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{7}
}

func (m *DeleteRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleResponse.Unmarshal(m, b)
}
func (m *DeleteRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleResponse.Merge(m, src)
}
func (m *DeleteRuleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleResponse.Size(m)
}
func (m *DeleteRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleResponse proto.InternalMessageInfo

func (m *DeleteRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProjectRulesRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectRulesRequest) Reset()         { *m = ProjectRulesRequest{} }
func (m *ProjectRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectRulesRequest) ProtoMessage()    {}
func (*ProjectRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{8}
}

func (m *ProjectRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRulesRequest.Unmarshal(m, b)
}
func (m *ProjectRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRulesRequest.Marshal(b, m, deterministic)
}
func (m *ProjectRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRulesRequest.Merge(m, src)
}
func (m *ProjectRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectRulesRequest.Size(m)
}
func (m *ProjectRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRulesRequest proto.InternalMessageInfo

func (m *ProjectRulesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectRulesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectRulesResponse) Reset()         { *m = ProjectRulesResponse{} }
func (m *ProjectRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectRulesResponse) ProtoMessage()    {}
func (*ProjectRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{9}
}

func (m *ProjectRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRulesResponse.Unmarshal(m, b)
}
func (m *ProjectRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRulesResponse.Marshal(b, m, deterministic)
}
func (m *ProjectRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRulesResponse.Merge(m, src)
}
func (m *ProjectRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectRulesResponse.Size(m)
}
func (m *ProjectRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRulesResponse proto.InternalMessageInfo

func (m *ProjectRulesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectRulesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectRulesResponse) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type CheckThingRuleRequest struct {
	Update               *Rule    `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckThingRuleRequest) Reset()         { *m = CheckThingRuleRequest{} }
func (m *CheckThingRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CheckThingRuleRequest) ProtoMessage()    {}
func (*CheckThingRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{10}
}

func (m *CheckThingRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckThingRuleRequest.Unmarshal(m, b)
}
func (m *CheckThingRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckThingRuleRequest.Marshal(b, m, deterministic)
}
func (m *CheckThingRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckThingRuleRequest.Merge(m, src)
}
func (m *CheckThingRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CheckThingRuleRequest.Size(m)
}
func (m *CheckThingRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckThingRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckThingRuleRequest proto.InternalMessageInfo

func (m *CheckThingRuleRequest) GetUpdate() *Rule {
	if m != nil {
		return m.Update
	}
	return nil
}

type CheckThingRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckThingRuleResponse) Reset()         { *m = CheckThingRuleResponse{} }
func (m *CheckThingRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CheckThingRuleResponse) ProtoMessage()    {}
func (*CheckThingRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{11}
}

func (m *CheckThingRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckThingRuleResponse.Unmarshal(m, b)
}
func (m *CheckThingRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckThingRuleResponse.Marshal(b, m, deterministic)
}
func (m *CheckThingRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckThingRuleResponse.Merge(m, src)
}
func (m *CheckThingRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CheckThingRuleResponse.Size(m)
}
func (m *CheckThingRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckThingRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckThingRuleResponse proto.InternalMessageInfo

func (m *CheckThingRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckThingRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateThingLinkRequest struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	PhysicalId           string   `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []string `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThingLinkRequest) Reset()         { *m = CreateThingLinkRequest{} }
func (m *CreateThingLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateThingLinkRequest) ProtoMessage()    {}
func (*CreateThingLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{12}
}

func (m *CreateThingLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingLinkRequest.Unmarshal(m, b)
}
func (m *CreateThingLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingLinkRequest.Marshal(b, m, deterministic)
}
func (m *CreateThingLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingLinkRequest.Merge(m, src)
}
func (m *CreateThingLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateThingLinkRequest.Size(m)
}
func (m *CreateThingLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingLinkRequest proto.InternalMessageInfo

func (m *CreateThingLinkRequest) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *CreateThingLinkRequest) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *CreateThingLinkRequest) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

type CreateThingLinkResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateThingLinkResponse) Reset()         { *m = CreateThingLinkResponse{} }
func (m *CreateThingLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CreateThingLinkResponse) ProtoMessage()    {}
func (*CreateThingLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{13}
}

func (m *CreateThingLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateThingLinkResponse.Unmarshal(m, b)
}
func (m *CreateThingLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateThingLinkResponse.Marshal(b, m, deterministic)
}
func (m *CreateThingLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateThingLinkResponse.Merge(m, src)
}
func (m *CreateThingLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CreateThingLinkResponse.Size(m)
}
func (m *CreateThingLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateThingLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateThingLinkResponse proto.InternalMessageInfo

func (m *CreateThingLinkResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateThingLinkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("ruleproto.Operation", Operation_name, Operation_value)
	proto.RegisterEnum("ruleproto.TriggerType", TriggerType_name, TriggerType_value)
	proto.RegisterType((*Channel)(nil), "ruleproto.Channel")
	proto.RegisterType((*TriggerCommand)(nil), "ruleproto.TriggerCommand")
	proto.RegisterType((*ThingChLink)(nil), "ruleproto.ThingChLink")
	proto.RegisterType((*Rule)(nil), "ruleproto.Rule")
	proto.RegisterType((*CreateRuleRequest)(nil), "ruleproto.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "ruleproto.CreateRuleResponse")
	proto.RegisterType((*DeleteRuleRequest)(nil), "ruleproto.DeleteRuleRequest")
	proto.RegisterType((*DeleteRuleResponse)(nil), "ruleproto.DeleteRuleResponse")
	proto.RegisterType((*ProjectRulesRequest)(nil), "ruleproto.ProjectRulesRequest")
	proto.RegisterType((*ProjectRulesResponse)(nil), "ruleproto.ProjectRulesResponse")
	proto.RegisterType((*CheckThingRuleRequest)(nil), "ruleproto.CheckThingRuleRequest")
	proto.RegisterType((*CheckThingRuleResponse)(nil), "ruleproto.CheckThingRuleResponse")
	proto.RegisterType((*CreateThingLinkRequest)(nil), "ruleproto.CreateThingLinkRequest")
	proto.RegisterType((*CreateThingLinkResponse)(nil), "ruleproto.CreateThingLinkResponse")
}

func init() { proto.RegisterFile("rule.proto", fileDescriptor_07e8e0fa338d4596) }

var fileDescriptor_07e8e0fa338d4596 = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x4f, 0xdb, 0x4a,
	0x10, 0xc6, 0x71, 0x9c, 0xc4, 0x63, 0xc8, 0x8f, 0x25, 0xe4, 0xed, 0x43, 0x4f, 0xef, 0x59, 0x7e,
	0xaa, 0x88, 0x38, 0xa4, 0x12, 0xbd, 0xf4, 0xd8, 0x28, 0x44, 0x05, 0x29, 0x90, 0x76, 0x71, 0xb9,
	0x9b, 0x64, 0x49, 0x0c, 0xc6, 0x76, 0xbd, 0x36, 0x12, 0x87, 0xfe, 0x33, 0xbd, 0xf6, 0x9f, 0xac,
	0x76, 0xd7, 0x8e, 0x37, 0xa1, 0x80, 0x94, 0xdb, 0xce, 0xcc, 0x37, 0xbb, 0xdf, 0x7c, 0x33, 0xb3,
	0x00, 0x49, 0x16, 0xd0, 0x41, 0x9c, 0x44, 0x69, 0x84, 0x4c, 0x7e, 0x16, 0x47, 0xe7, 0x97, 0x06,
	0xf5, 0xd1, 0xd2, 0x0b, 0x43, 0x1a, 0xa0, 0x26, 0x54, 0xfc, 0x39, 0xd6, 0x6c, 0xad, 0x6f, 0x92,
	0x8a, 0x3f, 0x47, 0xff, 0x02, 0xdc, 0x06, 0x91, 0x97, 0x5e, 0x7b, 0x41, 0x46, 0x71, 0xc5, 0xd6,
	0xfa, 0x1a, 0x51, 0x3c, 0xc8, 0x06, 0x8b, 0xa5, 0x89, 0x1f, 0x2e, 0x24, 0x40, 0x17, 0x89, 0xaa,
	0x0b, 0xfd, 0x03, 0xe6, 0x4d, 0x14, 0x05, 0x32, 0x5e, 0xb5, 0xb5, 0x7e, 0x83, 0x94, 0x0e, 0x1e,
	0x9d, 0x7b, 0xa9, 0x27, 0xa3, 0x86, 0xc8, 0x2e, 0x1d, 0x08, 0x41, 0x35, 0x0b, 0xfd, 0x14, 0xd7,
	0x6c, 0xad, 0x6f, 0x10, 0x71, 0x76, 0x1e, 0xa1, 0xe9, 0x26, 0xfe, 0x62, 0x41, 0x93, 0x51, 0xf4,
	0xf0, 0xe0, 0x85, 0x73, 0xd4, 0x05, 0x23, 0x5d, 0xfa, 0xe1, 0x22, 0xa7, 0x2d, 0x0d, 0xce, 0x3c,
	0x5e, 0x3e, 0x31, 0x7f, 0xe6, 0x05, 0xe7, 0x73, 0xc1, 0xdc, 0x24, 0x8a, 0x07, 0x0d, 0xa0, 0x31,
	0x93, 0x45, 0x33, 0xac, 0xdb, 0x7a, 0xdf, 0x3a, 0x41, 0x83, 0x95, 0x26, 0x83, 0x5c, 0x0f, 0xb2,
	0xc2, 0x38, 0xff, 0x81, 0xe5, 0xf2, 0x8b, 0x47, 0xcb, 0x89, 0x1f, 0xde, 0xa3, 0x36, 0xe8, 0xd9,
	0x4a, 0x29, 0x7e, 0x74, 0x7e, 0x1a, 0x50, 0x25, 0x59, 0x40, 0x9f, 0x69, 0xb8, 0xe2, 0x57, 0x51,
	0xf9, 0x61, 0xa8, 0xc7, 0x49, 0x74, 0x47, 0x67, 0x69, 0xae, 0x5a, 0x61, 0x6e, 0x68, 0x5e, 0x7d,
	0x4b, 0x73, 0xe3, 0x0d, 0xcd, 0x6b, 0xaf, 0x6a, 0x5e, 0x7f, 0x49, 0xf3, 0x46, 0xa9, 0x39, 0x3a,
	0x01, 0x33, 0x8a, 0x69, 0xe2, 0xa5, 0x7e, 0x14, 0x62, 0xd3, 0xd6, 0xfa, 0xcd, 0x93, 0xae, 0x22,
	0xd6, 0xb4, 0x88, 0x91, 0x12, 0x86, 0x3e, 0x82, 0x95, 0xca, 0x3e, 0xb9, 0x4f, 0x31, 0xc5, 0x20,
	0xb2, 0x7a, 0x4a, 0x96, 0x5b, 0x46, 0x89, 0x0a, 0x45, 0x23, 0x68, 0xa5, 0x6b, 0x1d, 0x66, 0xd8,
	0x12, 0x0d, 0xfa, 0xfb, 0x79, 0x76, 0x8e, 0x20, 0x9b, 0x19, 0x5c, 0xde, 0xbc, 0x75, 0x78, 0x57,
	0xca, 0x9b, 0x9b, 0xbc, 0x73, 0x8f, 0x5e, 0x80, 0xf7, 0x84, 0x2c, 0xfc, 0xc8, 0x4b, 0x7e, 0xf4,
	0x02, 0x86, 0x9b, 0x02, 0x28, 0xce, 0xe8, 0x1d, 0x18, 0xfc, 0x31, 0x86, 0x5b, 0xe2, 0xe9, 0x96,
	0xf2, 0x34, 0x6f, 0x32, 0x91, 0x51, 0x51, 0x65, 0x39, 0x15, 0xb8, 0x6d, 0x6b, 0x7d, 0x6b, 0xbd,
	0xca, 0x32, 0x4a, 0x54, 0x28, 0xea, 0x41, 0xcd, 0x67, 0x24, 0x8a, 0x52, 0xdc, 0x11, 0x4c, 0x72,
	0xab, 0x18, 0x2c, 0xb4, 0x1a, 0x2c, 0x89, 0x9c, 0x50, 0xef, 0x16, 0xef, 0x17, 0x48, 0x6e, 0x71,
	0xda, 0x09, 0xcf, 0xef, 0x4a, 0xda, 0xfc, 0xbc, 0x31, 0xf5, 0x07, 0x9b, 0x53, 0xef, 0x5c, 0x43,
	0x67, 0x94, 0x50, 0x2f, 0xa5, 0xa2, 0x08, 0xfa, 0x3d, 0xa3, 0x2c, 0x45, 0xff, 0x43, 0x95, 0x13,
	0x16, 0x23, 0xfb, 0x87, 0x52, 0x45, 0x90, 0x4f, 0x8d, 0xa0, 0xcf, 0x2e, 0xbc, 0x38, 0x9f, 0xe4,
	0xd2, 0xe1, 0xb8, 0x80, 0xd4, 0x7b, 0x59, 0x1c, 0x85, 0x8c, 0xf2, 0x26, 0xb0, 0x6c, 0x36, 0xa3,
	0x8c, 0x89, 0xbb, 0x1b, 0xa4, 0x30, 0xf9, 0x4e, 0xd0, 0x24, 0x89, 0x92, 0x62, 0x27, 0x84, 0x91,
	0x6f, 0x8e, 0x5e, 0x6c, 0x8e, 0x73, 0x04, 0x9d, 0x53, 0x1a, 0xd0, 0x75, 0xb6, 0x48, 0x61, 0x6b,
	0x4a, 0x72, 0xce, 0x29, 0x20, 0x15, 0xb8, 0xdd, 0xf3, 0xce, 0x7b, 0xd8, 0xff, 0x22, 0x77, 0x90,
	0x5f, 0xc3, 0x8a, 0x07, 0x95, 0x4d, 0xd5, 0xd6, 0x36, 0xd5, 0x79, 0x80, 0xee, 0x7a, 0xc2, 0x96,
	0x75, 0xaf, 0x86, 0x4d, 0x7f, 0x6d, 0xd8, 0x9c, 0x4f, 0x70, 0x30, 0x5a, 0xd2, 0xd9, 0xbd, 0x98,
	0x29, 0x55, 0x92, 0x23, 0xa8, 0x65, 0xf1, 0xdc, 0x4b, 0x5f, 0x6c, 0x61, 0x1e, 0x76, 0xce, 0xa0,
	0xb7, 0x79, 0xc3, 0x96, 0x5a, 0xdd, 0x41, 0x4f, 0x36, 0x5c, 0x5c, 0x25, 0xc6, 0x3b, 0x27, 0xb3,
	0xdd, 0x77, 0x7c, 0xb8, 0xf1, 0x1d, 0x9b, 0xca, 0xd7, 0x7b, 0x0e, 0x7f, 0x3d, 0x7b, 0x6b, 0x3b,
	0xda, 0xc7, 0x3f, 0xc0, 0x5c, 0xfd, 0x56, 0xc8, 0x04, 0x63, 0xfc, 0xf5, 0xdb, 0x70, 0xd2, 0xde,
	0x41, 0xbb, 0xd0, 0xb8, 0x9c, 0xba, 0xd2, 0xd2, 0xb8, 0x35, 0x19, 0x5f, 0x5d, 0xb9, 0x67, 0xc3,
	0xcb, 0x76, 0x05, 0x75, 0x60, 0xaf, 0xb0, 0x24, 0x40, 0x47, 0x2d, 0xb0, 0x3e, 0x93, 0xf1, 0xd0,
	0x1d, 0x13, 0x81, 0xa9, 0xa2, 0x2e, 0xb4, 0x15, 0x87, 0x84, 0x19, 0xa8, 0x0e, 0xfa, 0xf0, 0xf2,
	0xb4, 0x5d, 0x43, 0x35, 0xa8, 0x4c, 0x49, 0xbb, 0x7e, 0x7c, 0x08, 0x96, 0xf2, 0xed, 0x21, 0x0b,
	0xea, 0xa3, 0xe9, 0xc5, 0x05, 0xc7, 0xec, 0xdc, 0xd4, 0x44, 0xbf, 0x3e, 0xfc, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0xdb, 0xe5, 0xcb, 0xa6, 0x07, 0x00, 0x00,
}
