// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rule.proto

package ruleproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_EQUAL            Operation = 0
	Operation_NOTEQUAL         Operation = 1
	Operation_LESSTHAN         Operation = 2
	Operation_LESSTHANEQUAL    Operation = 3
	Operation_GREATERTHAN      Operation = 4
	Operation_GREATERTHANEQUAL Operation = 5
)

var Operation_name = map[int32]string{
	0: "EQUAL",
	1: "NOTEQUAL",
	2: "LESSTHAN",
	3: "LESSTHANEQUAL",
	4: "GREATERTHAN",
	5: "GREATERTHANEQUAL",
}

var Operation_value = map[string]int32{
	"EQUAL":            0,
	"NOTEQUAL":         1,
	"LESSTHAN":         2,
	"LESSTHANEQUAL":    3,
	"GREATERTHAN":      4,
	"GREATERTHANEQUAL": 5,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{0}
}

type TriggerType int32

const (
	TriggerType_COMMAND TriggerType = 0
)

var TriggerType_name = map[int32]string{
	0: "COMMAND",
}

var TriggerType_value = map[string]int32{
	"COMMAND": 0,
}

func (x TriggerType) String() string {
	return proto.EnumName(TriggerType_name, int32(x))
}

func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{1}
}

type Channel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,2,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,3,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,4,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,5,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32    `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ChannelFromBytes(data []byte) (*Channel, error) {
	t := &Channel{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Channel) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Channel) Reset()                   { *m = Channel{} }
func (m *Channel) String() string           { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()              {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{0}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type TriggerCommand struct {
	Thing                string     `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	Channels             []*Channel `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func TriggerCommandFromBytes(data []byte) (*TriggerCommand, error) {
	t := &TriggerCommand{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *TriggerCommand) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *TriggerCommand) Reset()                   { *m = TriggerCommand{} }
func (m *TriggerCommand) String() string           { return proto.CompactTextString(m) }
func (*TriggerCommand) ProtoMessage()              {}
func (*TriggerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{1}
}

func (m *TriggerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerCommand.Unmarshal(m, b)
}
func (m *TriggerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerCommand.Marshal(b, m, deterministic)
}
func (m *TriggerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerCommand.Merge(m, src)
}
func (m *TriggerCommand) XXX_Size() int {
	return xxx_messageInfo_TriggerCommand.Size(m)
}
func (m *TriggerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerCommand proto.InternalMessageInfo

func (m *TriggerCommand) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *TriggerCommand) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Rule struct {
	// @inject_tag: bson:"_id"
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Thing                string            `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Project              string            `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	FloatValue           float64           `protobuf:"fixed64,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string            `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool              `protobuf:"varint,6,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string            `protobuf:"bytes,7,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32             `protobuf:"varint,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Operation            Operation         `protobuf:"varint,9,opt,name=operation,proto3,enum=ruleproto.Operation" json:"operation,omitempty"`
	TriggerType          TriggerType       `protobuf:"varint,10,opt,name=triggerType,proto3,enum=ruleproto.TriggerType" json:"triggerType,omitempty"`
	TriggerCommands      []*TriggerCommand `protobuf:"bytes,11,rep,name=triggerCommands,proto3" json:"triggerCommands,omitempty"`
	Channel              string            `protobuf:"bytes,12,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func RuleFromBytes(data []byte) (*Rule, error) {
	t := &Rule{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *Rule) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *Rule) Reset()                   { *m = Rule{} }
func (m *Rule) String() string           { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()              {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{2}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Rule) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

func (m *Rule) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Rule) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Rule) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Rule) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Rule) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Rule) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *Rule) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_EQUAL
}

func (m *Rule) GetTriggerType() TriggerType {
	if m != nil {
		return m.TriggerType
	}
	return TriggerType_COMMAND
}

func (m *Rule) GetTriggerCommands() []*TriggerCommand {
	if m != nil {
		return m.TriggerCommands
	}
	return nil
}

func (m *Rule) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type CreateRuleRequest struct {
	Rule                 *Rule    `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateRuleRequestFromBytes(data []byte) (*CreateRuleRequest, error) {
	t := &CreateRuleRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateRuleRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateRuleRequest) Reset()                   { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string           { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()              {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{3}
}

func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(m, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type CreateRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CreateRuleResponseFromBytes(data []byte) (*CreateRuleResponse, error) {
	t := &CreateRuleResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CreateRuleResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CreateRuleResponse) Reset()                   { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string           { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()              {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{4}
}

func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(m, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

func (m *CreateRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRuleRequest struct {
	Rule                 string   `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteRuleRequestFromBytes(data []byte) (*DeleteRuleRequest, error) {
	t := &DeleteRuleRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteRuleRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteRuleRequest) Reset()                   { *m = DeleteRuleRequest{} }
func (m *DeleteRuleRequest) String() string           { return proto.CompactTextString(m) }
func (*DeleteRuleRequest) ProtoMessage()              {}
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{5}
}

func (m *DeleteRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleRequest.Unmarshal(m, b)
}
func (m *DeleteRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleRequest.Merge(m, src)
}
func (m *DeleteRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleRequest.Size(m)
}
func (m *DeleteRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleRequest proto.InternalMessageInfo

func (m *DeleteRuleRequest) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

type DeleteRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func DeleteRuleResponseFromBytes(data []byte) (*DeleteRuleResponse, error) {
	t := &DeleteRuleResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *DeleteRuleResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *DeleteRuleResponse) Reset()                   { *m = DeleteRuleResponse{} }
func (m *DeleteRuleResponse) String() string           { return proto.CompactTextString(m) }
func (*DeleteRuleResponse) ProtoMessage()              {}
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{6}
}

func (m *DeleteRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleResponse.Unmarshal(m, b)
}
func (m *DeleteRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleResponse.Merge(m, src)
}
func (m *DeleteRuleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleResponse.Size(m)
}
func (m *DeleteRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleResponse proto.InternalMessageInfo

func (m *DeleteRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProjectRulesRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectRulesRequestFromBytes(data []byte) (*ProjectRulesRequest, error) {
	t := &ProjectRulesRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectRulesRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectRulesRequest) Reset()                   { *m = ProjectRulesRequest{} }
func (m *ProjectRulesRequest) String() string           { return proto.CompactTextString(m) }
func (*ProjectRulesRequest) ProtoMessage()              {}
func (*ProjectRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{7}
}

func (m *ProjectRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRulesRequest.Unmarshal(m, b)
}
func (m *ProjectRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRulesRequest.Marshal(b, m, deterministic)
}
func (m *ProjectRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRulesRequest.Merge(m, src)
}
func (m *ProjectRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectRulesRequest.Size(m)
}
func (m *ProjectRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRulesRequest proto.InternalMessageInfo

func (m *ProjectRulesRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ProjectRulesResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func ProjectRulesResponseFromBytes(data []byte) (*ProjectRulesResponse, error) {
	t := &ProjectRulesResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *ProjectRulesResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *ProjectRulesResponse) Reset()                   { *m = ProjectRulesResponse{} }
func (m *ProjectRulesResponse) String() string           { return proto.CompactTextString(m) }
func (*ProjectRulesResponse) ProtoMessage()              {}
func (*ProjectRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{8}
}

func (m *ProjectRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectRulesResponse.Unmarshal(m, b)
}
func (m *ProjectRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectRulesResponse.Marshal(b, m, deterministic)
}
func (m *ProjectRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectRulesResponse.Merge(m, src)
}
func (m *ProjectRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectRulesResponse.Size(m)
}
func (m *ProjectRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectRulesResponse proto.InternalMessageInfo

func (m *ProjectRulesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectRulesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ProjectRulesResponse) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type CheckThingRuleRequest struct {
	Update               *Rule    `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CheckThingRuleRequestFromBytes(data []byte) (*CheckThingRuleRequest, error) {
	t := &CheckThingRuleRequest{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CheckThingRuleRequest) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CheckThingRuleRequest) Reset()                   { *m = CheckThingRuleRequest{} }
func (m *CheckThingRuleRequest) String() string           { return proto.CompactTextString(m) }
func (*CheckThingRuleRequest) ProtoMessage()              {}
func (*CheckThingRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{9}
}

func (m *CheckThingRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckThingRuleRequest.Unmarshal(m, b)
}
func (m *CheckThingRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckThingRuleRequest.Marshal(b, m, deterministic)
}
func (m *CheckThingRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckThingRuleRequest.Merge(m, src)
}
func (m *CheckThingRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CheckThingRuleRequest.Size(m)
}
func (m *CheckThingRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckThingRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckThingRuleRequest proto.InternalMessageInfo

func (m *CheckThingRuleRequest) GetUpdate() *Rule {
	if m != nil {
		return m.Update
	}
	return nil
}

type CheckThingRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func CheckThingRuleResponseFromBytes(data []byte) (*CheckThingRuleResponse, error) {
	t := &CheckThingRuleResponse{}
	err := proto.Unmarshal(data, t)
	return t, err
}

func (m *CheckThingRuleResponse) ToBytes() ([]byte, error) { return proto.Marshal(m) }
func (m *CheckThingRuleResponse) Reset()                   { *m = CheckThingRuleResponse{} }
func (m *CheckThingRuleResponse) String() string           { return proto.CompactTextString(m) }
func (*CheckThingRuleResponse) ProtoMessage()              {}
func (*CheckThingRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07e8e0fa338d4596, []int{10}
}

func (m *CheckThingRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckThingRuleResponse.Unmarshal(m, b)
}
func (m *CheckThingRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckThingRuleResponse.Marshal(b, m, deterministic)
}
func (m *CheckThingRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckThingRuleResponse.Merge(m, src)
}
func (m *CheckThingRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CheckThingRuleResponse.Size(m)
}
func (m *CheckThingRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckThingRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckThingRuleResponse proto.InternalMessageInfo

func (m *CheckThingRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckThingRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("ruleproto.Operation", Operation_name, Operation_value)
	proto.RegisterEnum("ruleproto.TriggerType", TriggerType_name, TriggerType_value)
	proto.RegisterType((*Channel)(nil), "ruleproto.Channel")
	proto.RegisterType((*TriggerCommand)(nil), "ruleproto.TriggerCommand")
	proto.RegisterType((*Rule)(nil), "ruleproto.Rule")
	proto.RegisterType((*CreateRuleRequest)(nil), "ruleproto.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "ruleproto.CreateRuleResponse")
	proto.RegisterType((*DeleteRuleRequest)(nil), "ruleproto.DeleteRuleRequest")
	proto.RegisterType((*DeleteRuleResponse)(nil), "ruleproto.DeleteRuleResponse")
	proto.RegisterType((*ProjectRulesRequest)(nil), "ruleproto.ProjectRulesRequest")
	proto.RegisterType((*ProjectRulesResponse)(nil), "ruleproto.ProjectRulesResponse")
	proto.RegisterType((*CheckThingRuleRequest)(nil), "ruleproto.CheckThingRuleRequest")
	proto.RegisterType((*CheckThingRuleResponse)(nil), "ruleproto.CheckThingRuleResponse")
}

func init() { proto.RegisterFile("rule.proto", fileDescriptor_07e8e0fa338d4596) }

var fileDescriptor_07e8e0fa338d4596 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0x8e, 0xbf, 0x00, 0x8f, 0xf3, 0x26, 0x30, 0x2f, 0x8d, 0xdc, 0xaa, 0xaa, 0x2c, 0x57, 0x55,
	0xac, 0x1c, 0xa8, 0x44, 0x2f, 0x39, 0x16, 0x19, 0xd4, 0x1c, 0x12, 0x68, 0x37, 0x6e, 0xee, 0x0e,
	0x6c, 0xc1, 0xad, 0xb1, 0x5d, 0x7b, 0x7d, 0xe8, 0x0f, 0xea, 0xa9, 0x7f, 0xb2, 0xf2, 0xae, 0x0d,
	0x0b, 0x28, 0x8d, 0xc4, 0x6d, 0x67, 0xe6, 0x79, 0xe6, 0xe3, 0x99, 0x59, 0x80, 0xbc, 0x8c, 0xe9,
	0x20, 0xcb, 0x53, 0x96, 0xa2, 0x59, 0xbd, 0xf9, 0xd3, 0xfd, 0xa3, 0x40, 0xdb, 0x5f, 0x85, 0x49,
	0x42, 0x63, 0x3c, 0x03, 0x35, 0x5a, 0xd8, 0x8a, 0xa3, 0x78, 0x26, 0x51, 0xa3, 0x05, 0xbe, 0x01,
	0xf8, 0x16, 0xa7, 0x21, 0x7b, 0x08, 0xe3, 0x92, 0xda, 0xaa, 0xa3, 0x78, 0x0a, 0x91, 0x3c, 0xe8,
	0x80, 0x55, 0xb0, 0x3c, 0x4a, 0x96, 0x02, 0xa0, 0x71, 0xa2, 0xec, 0xc2, 0xd7, 0x60, 0x3e, 0xa6,
	0x69, 0x2c, 0xe2, 0xba, 0xa3, 0x78, 0x1d, 0xb2, 0x75, 0x54, 0xd1, 0x45, 0xc8, 0x42, 0x11, 0x35,
	0x38, 0x7b, 0xeb, 0x40, 0x04, 0xbd, 0x4c, 0x22, 0x66, 0xb7, 0x1c, 0xc5, 0x33, 0x08, 0x7f, 0xbb,
	0x0f, 0x70, 0x16, 0xe4, 0xd1, 0x72, 0x49, 0x73, 0x3f, 0x5d, 0xaf, 0xc3, 0x64, 0x81, 0x7d, 0x30,
	0xd8, 0x2a, 0x4a, 0x96, 0x75, 0xdb, 0xc2, 0xc0, 0x01, 0x74, 0xe6, 0x62, 0xa8, 0xc2, 0x56, 0x1d,
	0xcd, 0xb3, 0x86, 0x38, 0xd8, 0xcc, 0x3c, 0xa8, 0xe7, 0x25, 0x1b, 0x8c, 0xfb, 0x5b, 0x03, 0x9d,
	0x94, 0x31, 0x3d, 0x90, 0x60, 0x93, 0x5e, 0x95, 0xd3, 0xdb, 0xd0, 0xce, 0xf2, 0xf4, 0x3b, 0x9d,
	0xb3, 0x7a, 0xe8, 0xc6, 0xdc, 0x93, 0x4c, 0x7f, 0x4e, 0x32, 0xe3, 0x19, 0xc9, 0x5a, 0xff, 0x94,
	0xac, 0xfd, 0x94, 0x64, 0x9d, 0xad, 0x64, 0x38, 0x04, 0x33, 0xcd, 0x68, 0x1e, 0xb2, 0x28, 0x4d,
	0x6c, 0xd3, 0x51, 0xbc, 0xb3, 0x61, 0x5f, 0xd2, 0x62, 0xd6, 0xc4, 0xc8, 0x16, 0x86, 0xd7, 0x60,
	0x31, 0x21, 0x73, 0xf0, 0x2b, 0xa3, 0x36, 0x70, 0xd6, 0x85, 0xc4, 0x0a, 0xb6, 0x51, 0x22, 0x43,
	0xd1, 0x87, 0x73, 0xb6, 0xb3, 0xa0, 0xc2, 0xb6, 0xb8, 0xfe, 0x2f, 0x0f, 0xd9, 0x35, 0x82, 0xec,
	0x33, 0x2a, 0x79, 0xeb, 0xcd, 0xd8, 0xa7, 0x42, 0xde, 0xda, 0x74, 0xaf, 0xa1, 0xe7, 0xe7, 0x34,
	0x64, 0xb4, 0x5a, 0x16, 0xa1, 0x3f, 0x4b, 0x5a, 0x30, 0x7c, 0x0b, 0x7a, 0x95, 0x9b, 0x6f, 0xcd,
	0x1a, 0x9e, 0x4b, 0x85, 0x38, 0x8a, 0x07, 0xdd, 0x00, 0x50, 0x66, 0x16, 0x59, 0x9a, 0x14, 0xb4,
	0xaa, 0x54, 0x94, 0xf3, 0x39, 0x2d, 0x0a, 0xce, 0xee, 0x90, 0xc6, 0xac, 0x16, 0x4f, 0xf3, 0x3c,
	0xcd, 0x9b, 0xc5, 0x73, 0xa3, 0x3e, 0x0f, 0xad, 0x39, 0x0f, 0xf7, 0x12, 0x7a, 0x63, 0x1a, 0xd3,
	0xdd, 0x7e, 0x50, 0xea, 0xc7, 0xac, 0xcb, 0x8f, 0x01, 0x65, 0xe0, 0x71, 0xe5, 0xdd, 0xf7, 0xf0,
	0xff, 0x67, 0x71, 0x68, 0x55, 0x9a, 0xa2, 0x29, 0x28, 0x9d, 0xa3, 0xb2, 0x73, 0x8e, 0xee, 0x1a,
	0xfa, 0xbb, 0x84, 0x23, 0xe7, 0x7e, 0x07, 0x46, 0x35, 0x46, 0x61, 0x6b, 0x7c, 0x99, 0x07, 0x1a,
	0x8b, 0xa8, 0xfb, 0x11, 0x5e, 0xf8, 0x2b, 0x3a, 0xff, 0x11, 0x54, 0xbf, 0x44, 0x96, 0xe4, 0x12,
	0x5a, 0x65, 0xb6, 0x08, 0xd9, 0x93, 0x4b, 0xaa, 0xc3, 0xee, 0x0d, 0x5c, 0xec, 0x67, 0x38, 0xae,
	0xe5, 0xab, 0x18, 0xcc, 0xcd, 0x6d, 0xa3, 0x09, 0xc6, 0xe4, 0xcb, 0xd7, 0xd1, 0x6d, 0xf7, 0x04,
	0x4f, 0xa1, 0x33, 0x9d, 0x05, 0xc2, 0x52, 0x2a, 0xeb, 0x76, 0x72, 0x7f, 0x1f, 0xdc, 0x8c, 0xa6,
	0x5d, 0x15, 0x7b, 0xf0, 0x5f, 0x63, 0x09, 0x80, 0x86, 0xe7, 0x60, 0x7d, 0x22, 0x93, 0x51, 0x30,
	0x21, 0x1c, 0xa3, 0x63, 0x1f, 0xba, 0x92, 0x43, 0xc0, 0x8c, 0xab, 0x57, 0x60, 0x49, 0x7f, 0x02,
	0x2d, 0x68, 0xfb, 0xb3, 0xbb, 0xbb, 0xd1, 0x74, 0xdc, 0x3d, 0x79, 0x6c, 0xf1, 0x39, 0x3f, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x90, 0x27, 0xf1, 0x7d, 0x82, 0x05, 0x00, 0x00,
}
