// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mqtt.proto

package mqttproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mqtt struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mqtt) Reset()         { *m = Mqtt{} }
func (m *Mqtt) String() string { return proto.CompactTextString(m) }
func (*Mqtt) ProtoMessage()    {}
func (*Mqtt) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{0}
}

func (m *Mqtt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mqtt.Unmarshal(m, b)
}
func (m *Mqtt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mqtt.Marshal(b, m, deterministic)
}
func (m *Mqtt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mqtt.Merge(m, src)
}
func (m *Mqtt) XXX_Size() int {
	return xxx_messageInfo_Mqtt.Size(m)
}
func (m *Mqtt) XXX_DiscardUnknown() {
	xxx_messageInfo_Mqtt.DiscardUnknown(m)
}

var xxx_messageInfo_Mqtt proto.InternalMessageInfo

func (m *Mqtt) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mqtt) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Mqtt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mqtt) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Channel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,2,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	StringValue          string   `protobuf:"bytes,3,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,4,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	DataValue            string   `protobuf:"bytes,5,opt,name=dataValue,proto3" json:"dataValue,omitempty"`
	Unit                 int32    `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{1}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *Channel) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Channel) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Channel) GetDataValue() string {
	if m != nil {
		return m.DataValue
	}
	return ""
}

func (m *Channel) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type Thing struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalId           string     `protobuf:"bytes,2,opt,name=physicalId,proto3" json:"physicalId,omitempty"`
	Channels             []*Channel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{2}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetPhysicalId() string {
	if m != nil {
		return m.PhysicalId
	}
	return ""
}

func (m *Thing) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type UpdateThingRequest struct {
	Thing                *Thing   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingRequest) Reset()         { *m = UpdateThingRequest{} }
func (m *UpdateThingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateThingRequest) ProtoMessage()    {}
func (*UpdateThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{3}
}

func (m *UpdateThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingRequest.Unmarshal(m, b)
}
func (m *UpdateThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingRequest.Merge(m, src)
}
func (m *UpdateThingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateThingRequest.Size(m)
}
func (m *UpdateThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingRequest proto.InternalMessageInfo

func (m *UpdateThingRequest) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type UpdateThingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateThingResponse) Reset()         { *m = UpdateThingResponse{} }
func (m *UpdateThingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateThingResponse) ProtoMessage()    {}
func (*UpdateThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{4}
}

func (m *UpdateThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateThingResponse.Unmarshal(m, b)
}
func (m *UpdateThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateThingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateThingResponse.Merge(m, src)
}
func (m *UpdateThingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateThingResponse.Size(m)
}
func (m *UpdateThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateThingResponse proto.InternalMessageInfo

func (m *UpdateThingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateThingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateMqttRequest struct {
	Mqtt                 *Mqtt    `protobuf:"bytes,1,opt,name=mqtt,proto3" json:"mqtt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMqttRequest) Reset()         { *m = CreateMqttRequest{} }
func (m *CreateMqttRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMqttRequest) ProtoMessage()    {}
func (*CreateMqttRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{5}
}

func (m *CreateMqttRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMqttRequest.Unmarshal(m, b)
}
func (m *CreateMqttRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMqttRequest.Marshal(b, m, deterministic)
}
func (m *CreateMqttRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMqttRequest.Merge(m, src)
}
func (m *CreateMqttRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMqttRequest.Size(m)
}
func (m *CreateMqttRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMqttRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMqttRequest proto.InternalMessageInfo

func (m *CreateMqttRequest) GetMqtt() *Mqtt {
	if m != nil {
		return m.Mqtt
	}
	return nil
}

type CreateMqttResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMqttResponse) Reset()         { *m = CreateMqttResponse{} }
func (m *CreateMqttResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMqttResponse) ProtoMessage()    {}
func (*CreateMqttResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{6}
}

func (m *CreateMqttResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMqttResponse.Unmarshal(m, b)
}
func (m *CreateMqttResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMqttResponse.Marshal(b, m, deterministic)
}
func (m *CreateMqttResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMqttResponse.Merge(m, src)
}
func (m *CreateMqttResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMqttResponse.Size(m)
}
func (m *CreateMqttResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMqttResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMqttResponse proto.InternalMessageInfo

func (m *CreateMqttResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateMqttResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateMqttResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserMqttsRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMqttsRequest) Reset()         { *m = UserMqttsRequest{} }
func (m *UserMqttsRequest) String() string { return proto.CompactTextString(m) }
func (*UserMqttsRequest) ProtoMessage()    {}
func (*UserMqttsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{7}
}

func (m *UserMqttsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMqttsRequest.Unmarshal(m, b)
}
func (m *UserMqttsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMqttsRequest.Marshal(b, m, deterministic)
}
func (m *UserMqttsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMqttsRequest.Merge(m, src)
}
func (m *UserMqttsRequest) XXX_Size() int {
	return xxx_messageInfo_UserMqttsRequest.Size(m)
}
func (m *UserMqttsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMqttsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserMqttsRequest proto.InternalMessageInfo

func (m *UserMqttsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type UserMqttsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Mqtts                []*Mqtt  `protobuf:"bytes,3,rep,name=mqtts,proto3" json:"mqtts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMqttsResponse) Reset()         { *m = UserMqttsResponse{} }
func (m *UserMqttsResponse) String() string { return proto.CompactTextString(m) }
func (*UserMqttsResponse) ProtoMessage()    {}
func (*UserMqttsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{8}
}

func (m *UserMqttsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMqttsResponse.Unmarshal(m, b)
}
func (m *UserMqttsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMqttsResponse.Marshal(b, m, deterministic)
}
func (m *UserMqttsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMqttsResponse.Merge(m, src)
}
func (m *UserMqttsResponse) XXX_Size() int {
	return xxx_messageInfo_UserMqttsResponse.Size(m)
}
func (m *UserMqttsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMqttsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserMqttsResponse proto.InternalMessageInfo

func (m *UserMqttsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserMqttsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UserMqttsResponse) GetMqtts() []*Mqtt {
	if m != nil {
		return m.Mqtts
	}
	return nil
}

type GetMqttRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMqttRequest) Reset()         { *m = GetMqttRequest{} }
func (m *GetMqttRequest) String() string { return proto.CompactTextString(m) }
func (*GetMqttRequest) ProtoMessage()    {}
func (*GetMqttRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{9}
}

func (m *GetMqttRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMqttRequest.Unmarshal(m, b)
}
func (m *GetMqttRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMqttRequest.Marshal(b, m, deterministic)
}
func (m *GetMqttRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMqttRequest.Merge(m, src)
}
func (m *GetMqttRequest) XXX_Size() int {
	return xxx_messageInfo_GetMqttRequest.Size(m)
}
func (m *GetMqttRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMqttRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMqttRequest proto.InternalMessageInfo

func (m *GetMqttRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetMqttRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetMqttResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Mqtt                 *Mqtt    `protobuf:"bytes,3,opt,name=mqtt,proto3" json:"mqtt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMqttResponse) Reset()         { *m = GetMqttResponse{} }
func (m *GetMqttResponse) String() string { return proto.CompactTextString(m) }
func (*GetMqttResponse) ProtoMessage()    {}
func (*GetMqttResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{10}
}

func (m *GetMqttResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMqttResponse.Unmarshal(m, b)
}
func (m *GetMqttResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMqttResponse.Marshal(b, m, deterministic)
}
func (m *GetMqttResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMqttResponse.Merge(m, src)
}
func (m *GetMqttResponse) XXX_Size() int {
	return xxx_messageInfo_GetMqttResponse.Size(m)
}
func (m *GetMqttResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMqttResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMqttResponse proto.InternalMessageInfo

func (m *GetMqttResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetMqttResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetMqttResponse) GetMqtt() *Mqtt {
	if m != nil {
		return m.Mqtt
	}
	return nil
}

type DeleteMqttRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMqttRequest) Reset()         { *m = DeleteMqttRequest{} }
func (m *DeleteMqttRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMqttRequest) ProtoMessage()    {}
func (*DeleteMqttRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{11}
}

func (m *DeleteMqttRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMqttRequest.Unmarshal(m, b)
}
func (m *DeleteMqttRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMqttRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMqttRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMqttRequest.Merge(m, src)
}
func (m *DeleteMqttRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMqttRequest.Size(m)
}
func (m *DeleteMqttRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMqttRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMqttRequest proto.InternalMessageInfo

func (m *DeleteMqttRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteMqttRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeleteMqttResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMqttResponse) Reset()         { *m = DeleteMqttResponse{} }
func (m *DeleteMqttResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMqttResponse) ProtoMessage()    {}
func (*DeleteMqttResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{12}
}

func (m *DeleteMqttResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMqttResponse.Unmarshal(m, b)
}
func (m *DeleteMqttResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMqttResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMqttResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMqttResponse.Merge(m, src)
}
func (m *DeleteMqttResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMqttResponse.Size(m)
}
func (m *DeleteMqttResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMqttResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMqttResponse proto.InternalMessageInfo

func (m *DeleteMqttResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteMqttResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateMqttRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMqttRequest) Reset()         { *m = UpdateMqttRequest{} }
func (m *UpdateMqttRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMqttRequest) ProtoMessage()    {}
func (*UpdateMqttRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{13}
}

func (m *UpdateMqttRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMqttRequest.Unmarshal(m, b)
}
func (m *UpdateMqttRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMqttRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMqttRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMqttRequest.Merge(m, src)
}
func (m *UpdateMqttRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMqttRequest.Size(m)
}
func (m *UpdateMqttRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMqttRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMqttRequest proto.InternalMessageInfo

func (m *UpdateMqttRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMqttRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UpdateMqttRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateMqttRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateMqttResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMqttResponse) Reset()         { *m = UpdateMqttResponse{} }
func (m *UpdateMqttResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMqttResponse) ProtoMessage()    {}
func (*UpdateMqttResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35327d90702720f6, []int{14}
}

func (m *UpdateMqttResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMqttResponse.Unmarshal(m, b)
}
func (m *UpdateMqttResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMqttResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMqttResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMqttResponse.Merge(m, src)
}
func (m *UpdateMqttResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMqttResponse.Size(m)
}
func (m *UpdateMqttResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMqttResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMqttResponse proto.InternalMessageInfo

func (m *UpdateMqttResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateMqttResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Mqtt)(nil), "mqttproto.Mqtt")
	proto.RegisterType((*Channel)(nil), "mqttproto.Channel")
	proto.RegisterType((*Thing)(nil), "mqttproto.Thing")
	proto.RegisterType((*UpdateThingRequest)(nil), "mqttproto.UpdateThingRequest")
	proto.RegisterType((*UpdateThingResponse)(nil), "mqttproto.UpdateThingResponse")
	proto.RegisterType((*CreateMqttRequest)(nil), "mqttproto.CreateMqttRequest")
	proto.RegisterType((*CreateMqttResponse)(nil), "mqttproto.CreateMqttResponse")
	proto.RegisterType((*UserMqttsRequest)(nil), "mqttproto.UserMqttsRequest")
	proto.RegisterType((*UserMqttsResponse)(nil), "mqttproto.UserMqttsResponse")
	proto.RegisterType((*GetMqttRequest)(nil), "mqttproto.GetMqttRequest")
	proto.RegisterType((*GetMqttResponse)(nil), "mqttproto.GetMqttResponse")
	proto.RegisterType((*DeleteMqttRequest)(nil), "mqttproto.DeleteMqttRequest")
	proto.RegisterType((*DeleteMqttResponse)(nil), "mqttproto.DeleteMqttResponse")
	proto.RegisterType((*UpdateMqttRequest)(nil), "mqttproto.UpdateMqttRequest")
	proto.RegisterType((*UpdateMqttResponse)(nil), "mqttproto.UpdateMqttResponse")
}

func init() { proto.RegisterFile("mqtt.proto", fileDescriptor_35327d90702720f6) }

var fileDescriptor_35327d90702720f6 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0x36, 0x9b, 0x76, 0x77, 0x56, 0x6a, 0x1b, 0xc3, 0x21, 0x07, 0x84, 0x22, 0x23, 0x50,
	0x4e, 0x39, 0x14, 0x09, 0x81, 0xc4, 0xad, 0x8b, 0x10, 0x07, 0x2e, 0x51, 0xcb, 0xdd, 0x9b, 0x4c,
	0x77, 0x8d, 0x52, 0x3b, 0x6b, 0x3b, 0x42, 0xfc, 0x26, 0xfe, 0x24, 0xb2, 0x9d, 0xa4, 0xae, 0x8a,
	0x50, 0x09, 0x37, 0xcf, 0x9b, 0x8f, 0xf7, 0xe6, 0x23, 0x01, 0xb8, 0x3b, 0x1a, 0x53, 0x76, 0x4a,
	0x1a, 0x49, 0xd6, 0xf6, 0xed, 0x9e, 0x74, 0x07, 0xcb, 0xaf, 0x47, 0x63, 0xc8, 0x19, 0x2c, 0x78,
	0x93, 0x45, 0x79, 0x54, 0xac, 0xab, 0x05, 0x6f, 0xc8, 0x73, 0x48, 0xe4, 0x0f, 0x81, 0x2a, 0x5b,
	0x38, 0xc8, 0x1b, 0x84, 0xc0, 0x52, 0xb0, 0x3b, 0xcc, 0x62, 0x07, 0xba, 0x37, 0xc9, 0x61, 0xd3,
	0xa0, 0xae, 0x15, 0xef, 0x0c, 0x97, 0x22, 0x5b, 0x3a, 0x57, 0x08, 0xd1, 0x5f, 0x11, 0x9c, 0x5e,
	0x1d, 0x98, 0x10, 0xd8, 0x3e, 0xe2, 0x79, 0x09, 0x70, 0xdb, 0x4a, 0x66, 0xbe, 0xb1, 0xb6, 0x47,
	0x47, 0x16, 0x55, 0x01, 0x62, 0xab, 0x6b, 0xa3, 0xb8, 0xd8, 0xfb, 0x00, 0x4f, 0x1c, 0x42, 0xe4,
	0x05, 0xac, 0x77, 0x52, 0xb6, 0xde, 0x6f, 0xd9, 0x57, 0xd5, 0x3d, 0x60, 0xbd, 0x0d, 0x33, 0xcc,
	0x7b, 0x13, 0x97, 0x7d, 0x0f, 0xd8, 0x7e, 0x7a, 0xc1, 0x4d, 0x76, 0x92, 0x47, 0x45, 0x52, 0xb9,
	0x37, 0xdd, 0x43, 0x72, 0x7d, 0xe0, 0x62, 0xff, 0x27, 0xa9, 0xdd, 0xe1, 0xa7, 0xe6, 0x35, 0x6b,
	0xbf, 0x34, 0xc3, 0x5c, 0x02, 0x84, 0x94, 0xb0, 0xaa, 0x7d, 0x97, 0x3a, 0x8b, 0xf3, 0xb8, 0xd8,
	0x5c, 0x92, 0x72, 0x1a, 0x74, 0x39, 0x0c, 0xa0, 0x9a, 0x62, 0xe8, 0x47, 0x20, 0x37, 0x5d, 0xc3,
	0x0c, 0x3a, 0xba, 0x0a, 0x8f, 0x3d, 0x6a, 0x43, 0xde, 0x40, 0x62, 0xac, 0xed, 0x88, 0x37, 0x97,
	0x17, 0x41, 0x09, 0x1f, 0xe7, 0xdd, 0xf4, 0x13, 0x3c, 0x7b, 0x90, 0xad, 0x3b, 0x29, 0x34, 0x92,
	0x0c, 0x4e, 0x75, 0x5f, 0xd7, 0xa8, 0xb5, 0x2b, 0xb0, 0xaa, 0x46, 0xd3, 0x6e, 0x14, 0x95, 0x92,
	0xd3, 0x46, 0x9d, 0x41, 0xdf, 0x43, 0x7a, 0xa5, 0x90, 0x19, 0xb4, 0x57, 0x30, 0x6a, 0x78, 0x05,
	0x4b, 0xcb, 0x3a, 0x48, 0x38, 0x0f, 0x24, 0xb8, 0x28, 0xe7, 0xa4, 0xd7, 0x40, 0xc2, 0xcc, 0x79,
	0xfc, 0xc3, 0x90, 0xe3, 0x71, 0xc8, 0xb4, 0x80, 0x8b, 0x1b, 0x8d, 0xca, 0xd6, 0xd4, 0xa3, 0x9c,
	0xe9, 0x16, 0xa3, 0xe0, 0x16, 0xe9, 0x77, 0x48, 0x83, 0xc8, 0x99, 0xf4, 0xaf, 0x21, 0xb1, 0xcd,
	0x8c, 0x0b, 0x7b, 0xd4, 0xaa, 0xf7, 0xd2, 0x77, 0x70, 0xf6, 0x19, 0x4d, 0x38, 0xa2, 0x27, 0x7d,
	0x2f, 0xf4, 0x16, 0xce, 0xa7, 0xbc, 0x99, 0x0a, 0xc7, 0x5d, 0xc4, 0x7f, 0xdb, 0xc5, 0x07, 0x48,
	0xb7, 0xd8, 0xe2, 0xc3, 0x2d, 0x3e, 0x4d, 0xe2, 0x16, 0x48, 0x98, 0x3a, 0xf3, 0x8c, 0x24, 0xa4,
	0xfe, 0x1a, 0xff, 0x59, 0xc0, 0xcc, 0x7f, 0xca, 0x76, 0xfc, 0x78, 0xfe, 0x47, 0xf6, 0xee, 0xc4,
	0x4d, 0xf2, 0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xff, 0x9d, 0x4b, 0x1d, 0x05, 0x00,
	0x00,
}
